### PR TITLE
fix: Fix StyledText style inheritance rules (click/hover event, font, insertion inheritance)

### LINKED ISSUE #2126: `StyledText` doesn't handle inherited hover/click effects
`StyledText.fromComponent` will fail to transfer all hover and click events of the original message (See example below).

Example

### PR DESCRIPTION
**Pull request by kristofbolyai**
Fixes https://github.com/Wynntils/Artemis/issues/2126

### CODE REVIEW

File: common/src/main/java/com/wynntils/core/text/PartStyle.java [hunk 1]
```diff
@@ -68,13 +68,6 @@ static PartStyle fromStyle(Style style, StyledTextPart owner, Style parentStyle)
         } else {
             // This changes properties that are null, as-in, inherting from the previous style.
             inheritedStyle = style.applyTo(parentStyle);
-
-            // We don't want to inherit these properties.
-            inheritedStyle = inheritedStyle
-                    .withClickEvent(style.getClickEvent())
-                    .withHoverEvent(style.getHoverEvent())
-                    .withInsertion(style.getInsertion())
-                    .withFont(style.getFont());
```
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/core/text/PartStyle.java:77]: I was too fast to read the code of Style when I first wrote this.. so I made the mistake of not inheriting this.

File: fabric/src/test/java/TestStyledText.java [hunk 2]
```diff
@@ -522,4 +522,19 @@ public void styledText_getStringWithNonChatFormattingColors() {
...
+    @Test
+    public void styledText_inheritesHoverEvents() {
+        final Component component = Component.empty()
+                .withStyle(style ->
+                        style.withHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT, Component.literal("hover"))))
+                .append(Component.literal("inherited hover effect"));
+
+        StyledText styledText = StyledText.fromComponent(component);
+
+        Assertions.assertEquals(
```
Comment (magicus) [inline fabric/src/test/java/TestStyledText.java:535]: Just want to check: without the fix, does the test fail?

Comment (kristofbolyai) [reply fabric/src/test/java/TestStyledText.java:535]: Yes. That is what causes tue linked issue. I suspected it after  I looked at it, and it was easy to confirm.

**Review by magicus — APPROVED** [review]
