### PR TITLE
fix: incomplete SpellInputsSegment

### LINKED ISSUE #3940: SpellEvent.Completed/Failed doesn't fire anymore
Since v2.2.0 Wynncraft has updated the actionbar to instantly show the resolved spell after the input sequence.
This means that [SpellModel.java#L236](https://github.com/Wynntils/Wynntils/blob/main/common/src/main/java/com/wynntils/models/spells/SpellModel.java#L236) will never have a length of 3.

### PR DESCRIPTION
**Pull request by Flonja**
Closes #3940

### CODE REVIEW

**Review by ShadowCat117 — CHANGES_REQUESTED** [review]
Thank you for the contribution, though this isn't the right way to fix it. Instead the logic for handling the final input should be handled in https://github.com/Wynntils/Wynntils/blob/main/common/src/main/java/com/wynntils/models/spells/SpellModel.java#L266, as we know 3 inputs have now been sent and as we know which spell was cast we can find the final input from that

**Comment by Flonja** [comment]
My bad, must've read past it I guess

File: common/src/main/java/com/wynntils/models/spells/SpellModel.java [hunk 1]
```diff
@@ -267,6 +267,8 @@ private void handleSpellCast(SpellCastSegment spellCastSegment) {
         if (spellTextActive) return;
 
         spellTextActive = true;
+        updateFromSpellSegment(
+                new SpellInputsSegment("", 0, 0, spellCastSegment.getSpellType().getSpellDirectionArray()));
```
Comment (ShadowCat117) [inline common/src/main/java/com/wynntils/models/spells/SpellModel.java]: Making a new segment here isn't great. What I'd do instead is take the logic out of `updateFromSpellSegment` and make a new method that only takes in the directions array, then you can call that from here and make `updateFromSpellSegment` call that too

Comment (ShadowCat117) [reply common/src/main/java/com/wynntils/models/spells/SpellModel.java]: So anything that needs details from the segment can remain in `updateFromSpellSegment`, anything that just needs the spell directions can go in this new `updateFromSpellArray` or whatever you decide to call it

Comment (Flonja) [reply common/src/main/java/com/wynntils/models/spells/SpellModel.java]: ~~I'll just change the `updateFromSpellSegment` to take `SpellDirection[] directions` instead then~~
The second message didn't show up, will do that now

**Comment by Flonja** [comment]
I just play tested and while it does work, it has some visual issues (ex. overlapping the casted spell with the input)

**Comment by ShadowCat117** [comment]
Ok so the overlays need their logic for reseting on partial/completed cast fixed up a bit

**Comment by Flonja** [comment]
I got stuck on a lot of debugging, which is why this PR got turned back into a draft.
It should all be good now! :D

**Review by ShadowCat117 — APPROVED** [review]
Seems good now, thanks!
