### PR TITLE
fix: Fix translation feature triggering events from translated message

### LINKED ISSUE #3590: Translation feature is handling already translated messages, leading to crashes
Translation feature translates message, sends translated message to client, feature then recieves the chat event for this new message and repeats this process until the client crashes

### PR DESCRIPTION
**Pull request by ShadowCat117**
Fixes https://github.com/Wynntils/Wynntils/issues/3590

### CODE REVIEW

File: common/src/main/java/com/wynntils/features/utilities/TranslationFeature.java [hunk 1]
```diff
@@ -71,7 +71,10 @@ public void onChat(ChatMessageEvent.Match e) {
                         // We failed to get a translation; send the original message so it's not lost
                         messageToSend = originalMessage;
                     }
-                    McUtils.mc().doRunTask(() -> McUtils.sendMessageToClient(messageToSend.getComponent()));
+                    McUtils.mc().doRunTask(() -> {
+                        // We need this to not trigger any events so don't use McUtils.sendMessageToClient
```
Comment (magicus) [inline common/src/main/java/com/wynntils/features/utilities/TranslationFeature.java:75]: This will probably not work with chat tabs. It's also unclear what the expected behavior should be with chat tabs..?

Comment (ShadowCat117) [reply common/src/main/java/com/wynntils/features/utilities/TranslationFeature.java:75]: Hmm, I'd be ok if they just filtered into the all tab for now, but if they won't show up in any then we'll need a better fix..

Comment (magicus) [reply common/src/main/java/com/wynntils/features/utilities/TranslationFeature.java:75]: Afaik all tabs are configurable so the user might not even have an "All" tab. But I believe what would happen with the code above is that it will reach no tabs at all, but disappear in a black hole in the wrapper chat handler.

I think the "proper" behavior should be for translated messages to appear in the same tab as the original message? If so, then maybe the responsibility to request a translation must lie with the chat tab that recieves a messages. Or we need to keep a connection to the original message, send out a pair with <original, translation> and have chat tabs look for the original message, and if found, also add the translated one.

Comment (ShadowCat117) [reply common/src/main/java/com/wynntils/features/utilities/TranslationFeature.java:75]: Ok I just went back to before all of your chat changes and this functions exactly the same as it did back then so I think it's fine to just get this released to make the feature at least barely useable and then whenever someone wants to take up the monumentous task of fixing the translation feature it could be looked at better then

Comment (ShadowCat117) [reply common/src/main/java/com/wynntils/features/utilities/TranslationFeature.java:75]: For reference the original functionality was that the translated message ends up in the All tab and the original message (even if the keep original setting is disabled) ends up in the intended chat tab

**Review by magicus — APPROVED** [review]
