### PR TITLE
fix: fix inventory emerald count being wrong, container not being counted

### LINKED ISSUE #1548: EmeraldCountFeature doesn't correctly keep track on the emeralds in the player's inventory
When slicing the itemStack by right-clicking the counter doesn't update.
It also doesn't count the emeralds on the cursor.
Because the sever only sends ClientboundContainerSetSlotPackets when the prediction of the client is false, a solution has to listen to both ServerboundContainerClickPacket(e.g. using mixins in MultiPlayerGameMode#handleInventoryMouseClick) and ClientboundContainerSetSlotPacket(e.g. using ContainerSetSlotEvent).

### PR DESCRIPTION
**Pull request by kristofbolyai**
Fixes https://github.com/Wynntils/Artemis/issues/1548.

**Review by commit.** Yes, all of these are needed for this to reliably work, Minecraft does have a lot of cases for ItemStack count updates, it's impossible to catch all of them. So we use a supplier.

I also moved to the tick method in emerald model, since we don't do any parsing there anymore (unlike when it was written) it is probably even faster than 90 set slots.

### CODE REVIEW

**Comment by Mcrtin** [comment]
Instead of getting the emerald amount from the count, can we not calculate it through the lore? As far as I can remember, the emerald itemStack always displays its value and we can divide that by the EmeraldUnit. What am I missing?

File: common/src/main/java/com/wynntils/models/emeralds/EmeraldModel.java [hunk 1]
```diff
@@ -50,6 +50,93 @@ public EmeraldModel(CharacterModel characterModel, ItemModel itemModel) {
...
+            for (ItemStack item : items) {
+                adjustBalance(null, item, false);
+            }
+        }
+    }
+
+    @SubscribeEvent
+    public void onMenuOpened(MenuEvent.MenuOpenedEvent e) {
+        String title = WynnUtils.normalizeBadString(e.getTitle().getString());
+        if (title.equals("Emerald Pouch")) {
```
Comment (ShadowCat117) [inline common/src/main/java/com/wynntils/models/emeralds/EmeraldModel.java:86]: Worth making this a constant? Think we do that in most other places

**Comment by kristofbolyai** [comment]
> Instead of getting the emerald amount from the count, can we not calculate it through the lore? As far as I can remember, the emerald itemStack always displays its value and we can divide that by the EmeraldUnit. What am I missing?

Wynn is bugged and doesn't update the lore

File: common/src/main/java/com/wynntils/models/emeralds/EmeraldModel.java (hunk 1 above)
Comment (kristofbolyai) [reply common/src/main/java/com/wynntils/models/emeralds/EmeraldModel.java:86]: Perhaps but this is a move, not a change.

**Comment by ShadowCat117** [comment]
Inventory emerald count seems to be getting rendered on all containers

**Comment by kristofbolyai** [comment]
Fixed the container count. I think this is a safe way to do it, since the container always has our inventory contents as well.

**Review by ShadowCat117 — APPROVED** [review]

File: common/src/main/java/com/wynntils/models/items/items/game/EmeraldItem.java [hunk 2]
```diff
@@ -6,18 +6,19 @@
 
 import com.wynntils.models.emeralds.type.EmeraldUnits;
 import com.wynntils.models.items.properties.EmeraldValuedItemProperty;
+import java.util.function.Supplier;
 
 public class EmeraldItem extends GameItem implements EmeraldValuedItemProperty {
-    private final int amount;
+    private final Supplier<Integer> amountSupplier;
```
Comment (magicus) [inline common/src/main/java/com/wynntils/models/items/items/game/EmeraldItem.java:12]: I am a bit skeptical to this. Up until now, item annotations have always been immutable. Now the value returned by getAmount() can suddenly start varying from call to call on the same EmeraldItem.

I hear what you say that there are a lot of cases where the item count is changed. But then maybe the actual amount should perhaps not be part of the EmeraldItem at all, but have like a EmeraldModel.getAmount(ItemStack item). It is a bit sad if the EmeraldItem cannot describe its actual value, and just the unit, but if we can't guarantee that it is unchanging, then I think that is a better path to take.

Comment (magicus) [reply common/src/main/java/com/wynntils/models/items/items/game/EmeraldItem.java:12]: (But best would be to actually catch all count changes)
