### PR TITLE
fix: Update GearType ItemStack parsing

### LINKED ISSUE #3452: GearType needs to be updated to support new gear ItemStacks
This is causing UnknownGearAnnotator to not function as `GearType gearType = GearType.fromItemStack(itemStack);` is always returning null.

### PR DESCRIPTION
**Pull request by ShadowCat117**
Fixes https://github.com/Wynntils/Wynntils/issues/3452

Depends on https://github.com/Wynntils/Static-Storage/pull/328

### CODE REVIEW

File: common/src/main/java/com/wynntils/models/gear/type/GearType.java [hunk 1]
```diff
@@ -85,21 +95,43 @@ public enum GearType {
...
         this.classReq = classReq;
         this.defaultItem = defaultItem;
-        this.models = firstModel == 0 && lastModel == 0
-                ? List.of()
-                : IntStream.rangeClosed(firstModel, lastModel)
-                        .mapToObj(i -> (float) i)
-                        .toList();
+        List<Float> modelList = new ArrayList<>();
+
+        if (!(firstModel == 0 && lastModel == 0)) {
```
Comment (magicus) [inline common/src/main/java/com/wynntils/models/gear/type/GearType.java]: Maybe de Morgan this? firstModel != 0 || lastModel != 0 seems easier to read to me. Also, from the look of the data, it seems like it should be enough to test one of them..?

Comment (ShadowCat117) [reply common/src/main/java/com/wynntils/models/gear/type/GearType.java]: Not sure what I was doing writing it like that 🤔 

And yeah, can make it only check 1, only made it check both as that's what it was doing previously

**Review by magicus — COMMENTED** [review]
That looks better. I can't really judge the rest of the code, I don't understand the new format.

**Comment by ShadowCat117** [comment]
It's essentially, all items are potions except armour which are always leather armour except for crafted armour which still uses leather-diamond. And then to determine which texture they use, they set a custom model data value.

For armour there's 18 variants so 1-18 is the range we check, for weapons and accessories the range is just dependent on whatever they set in the resource pack, if a new item comes at a lower number then these will all need to be bumped. I presume it's ordered alphabetically but haven't checked.

Then since skins are also potions, the helmet needs a separate range for the skins as otherwise it would be covering values that aren't actually helmets

**Comment by ShadowCat117** [comment]
This probably needs another update after the newest patch.

Was the original intention behind the UnknownGearAnnotator for items not present/updated in the API or for players who fail to download the cache so that weapon checks for example can still work?

If the former, it might be worth changing this to use https://github.com/Wynntils/Static-Storage/blob/main/Data-Storage/model_data.json so that we can push updates more easily though it might look as nice when implemented

**Comment by ShadowCat117** [comment]
This version should work in theory, need the static storage pr merged to test it though.

If it works, then this means we can update these values without needing to release a new version, but if users fail to download the data then it will fail to identify items

File: common/src/main/java/com/wynntils/models/gear/type/GearType.java [hunk 2]
```diff
@@ -19,87 +17,116 @@
 import net.minecraft.world.item.component.CustomModelData;
 
 public enum GearType {
-    SPEAR(ClassType.WARRIOR, Items.IRON_HORSE_ARMOR, 437, 497, 0),
-    WAND(ClassType.MAGE, Items.IRON_HORSE_ARMOR, 308, 372, 1),
-    DAGGER(ClassType.ASSASSIN, Items.IRON_HORSE_ARMOR, 244, 307, 2),
-    BOW(ClassType.ARCHER, Items.IRON_HORSE_ARMOR, 182, 243, 3),
-    RELIK(ClassType.SHAMAN, Items.IRON_HORSE_ARMOR, 373, 436, 4),
+    SPEAR(ClassType.WARRIOR, ModelSupplier.forKey("spear_min"), ModelSupplier.forKey("spear_max"), 0),
```
Comment (magicus) [inline common/src/main/java/com/wynntils/models/gear/type/GearType.java]: I had missed ModelSupplier. I am not really happy with that API. The factory method should be ` Services.CustomModel.getSupplierForKey()` or something like that instead. Now the CustomModel service is just completely hidden from view... I'm not saying you need to fix it in this PR, but I won't hold it against you if you do. :)

Comment (magicus) [reply common/src/main/java/com/wynntils/models/gear/type/GearType.java]: Also, just to be clear I understand the intent here: We want to move these constants out of the mod into a json file, and the reason is not so much that it easier to update the json files than then java code (it really is not, almost the contrary), but that we think that people will not update the mod if the constants need updating (which can happen with a new resource pack). 

Did I get that right?

Comment (ShadowCat117) [reply common/src/main/java/com/wynntils/models/gear/type/GearType.java]: Yeah, this way users running older versions will still have the latest values for these as a decent amount of people do stay on older versions, see the playground channel in the dev server.

It's just nicer than having to do a new release when this may be the only change needed

Comment (ShadowCat117) [reply common/src/main/java/com/wynntils/models/gear/type/GearType.java]: How's 90888957eed5017c518aae42c4ba6888a29c25bc

File: common/src/main/java/com/wynntils/models/gear/type/GearType.java [hunk 3]
```diff
@@ -218,31 +209,23 @@ public boolean isValidWeapon(ClassType classType) {
...
+            addRangeToList(skinModelRange, tempModelList);
 
-            modelList = List.copyOf(tmp);
+            modelList = List.copyOf(tempModelList);
         }
+
         return modelList;
     }
+
+    private static void addRangeToList(Supplier<Optional<Pair<Float, Float>>> supplier, List<Float> out) {
```
Comment (magicus) [inline common/src/main/java/com/wynntils/models/gear/type/GearType.java]: Do we need to do this with suppliers instead of "burning in" the actual data at a suitable time (like construction)? In general, I don't like suppliers. The added flexibility can be great when really needed, but it makes it much harder to reason about the code and to analyze it in a static context. My understanding here is that this is just reflecting values from a json file we have read in, so there seems to be no need of this flexibility.

File: common/src/main/java/com/wynntils/models/gear/type/GearType.java [hunk 4]
```diff
@@ -19,87 +19,104 @@
...
             List<Item> otherItems,
             int encodingId) {
         this.classReq = classReq;
         this.defaultItem = defaultItem;
-        this.models = firstModel == 0 && lastModel == 0
-                ? List.of()
-                : IntStream.rangeClosed(firstModel, lastModel)
-                        .mapToObj(i -> (float) i)
-                        .toList();
+        this.modelKey = modelKey;
```
Comment (magicus) [inline common/src/main/java/com/wynntils/models/gear/type/GearType.java:107]: So what I meant was that modelRange should be a `Optional<Pair<Float, Float>>`, not a `Supplier<Optional<Pair<Float, Float>>>`, and that you should resolve it here already.

Or is the problem that the json file might not be loaded when you try to access the GearType the first time?

Comment (ShadowCat117) [reply common/src/main/java/com/wynntils/models/gear/type/GearType.java:107]: We won't be able to access the json until the service has been initalized and the download finished

Comment (magicus) [reply common/src/main/java/com/wynntils/models/gear/type/GearType.java:107]: Hm. In that case, I think we should redesign the responsibility for looking up these model ranges. Let me think a bit about it. I can accept the current PR in the meantime, and refactor later as well.

**Comment by ShadowCat117** [comment]
This is ready if we're happy with the json format and the handling of looking up the values for now at least

File: common/src/main/java/com/wynntils/models/gear/type/GearType.java [hunk 5]
```diff
@@ -110,37 +127,42 @@ public static GearType fromString(String typeStr) {
...
 
-        // Gears have a lot of different skinned items, checking for the string in lore is more reliable
-        List<StyledText> lore = LoreUtils.getLore(itemStack);
-        if (!lore.isEmpty()) {
-            Matcher matcher = lore.getLast().getMatcher(SKINNED_GEAR_PATTERN);
-            if (matcher.matches()) {
-                return GearType.fromString(matcher.group(1));
+                if (damage >= 1 && damage <= 17) return RING;
+                if (damage >= 18 && damage <= 34) return NECKLACE;
+                if (damage >= 35 && damage <= 49) return BRACELET;
```
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/models/gear/type/GearType.java]: Can we make a static map for this, or anything so it is extracted out of here?

**Comment by ShadowCat117** [comment]
New model values https://github.com/Wynntils/Static-Storage/pull/337

**Review by magicus — APPROVED** [review]
