### PR TITLE
fix: Rich presence without library crashes config system

### LINKED ISSUE #1917: DiscordRichPresence will crash when no valid version of GLIBC is found
```
[19:19:42] [Render thread/ERROR]: Failed to initialize Wynntils features
java.lang.UnsatisfiedLinkError: /tmp/java-discord-game-sdk-32228091688074/libdiscord_game_sdk_jni.so: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/java-discord-game-sdk-32228091688074/libdiscord_game_sdk_jni.so)
```

Simply, the `discord_game_sdk_jni.so` requires version 2.34 of glibc, which is apparently not present on my system. This will crash every time the config is loaded, which includes saving the content book causing other changes not to be saved.

I got a quick workaround working by try-catching the error and disabling the feature, though this is very dirty and I assume a more solution should exist.

The quick and dirty try-catch ([DiscordRichPresenceFeature.java:127](https://github.com/Wynntils/Artemis/blob/3052ca7ab7c9a7c9833f98f53fa11fe5f0e53b06/common/src/main/java/com/wynntils/features/DiscordRichPresenceFeature.java#L127C3-L127C3))
```java
protected void onConfigUpdate(ConfigHolder configHolder) {                                                                                                                                            
         if (this.isEnabled()) {                                                                                                                                                                           
             // This isReady() check is required for Linux to not crash on config change.                                                                                                                  
             if (!Services.Discord.isReady()) {                                                                                                                                                            
                try{                                                                                                                                                                                       
                     // Even though this is in the onConfigUpdate method, it is how the library is first loaded on launch                                                                                  
                     Services.Discord.load(); 
                 }catch(UnsatisfiedLinkError e){                                                                                                                                                           
                     WynntilsMod.getLogger().warn("Failed setting up discord rich presence: {}", e.getMessage());                                                                                          
                     Managers.Feature.disableFeature(this);
                     return; 
                 }                                                                                                                                                                                       
             }                                                                                                                                                                                           

```

The full backtrace:

```
[19:19:42] [Render thread/ERROR]: Failed to initialize Wynntils features
java.lang.UnsatisfiedLinkError: /tmp/java-discord-game-sdk-32228091688074/libdiscord_game_sdk_jni.so: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/java-discord-game-sdk-32228091688074/libdiscord_game_sdk_jni.so)
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
	at java.lang.System.load(System.java:1953) ~[?:?]
	at com.wynntils.antiope.core.DiscordGameSDKCore.loadLibrary(DiscordGameSDKCore.java:97) ~[wynntils-0.0.3-SNAPSHOT-fabric+MC-1.19.4.jar:?]
	at com.wynntils.services.discord.DiscordService.load(DiscordService.java:35) ~[wynntils-0.0.3-SNAPSHOT-fabric+MC-1.19.4.jar:?]
	at com.wynntils.features.DiscordRichPresenceFeature.onConfigUpdate(DiscordRichPresenceFeature.java:135) ~[wynntils-0.0.3-SNAPSHOT-fabric+MC-1.19.4.jar:?]
	at com.wynntils.core.consumers.features.Feature.updateConfigOption(Feature.java:91) ~[wynntils-0.0.3-SNAPSHOT-fabric+MC-1.19.4.jar:?]
	at com.wynntils.core.config.ConfigHolder.setValue(ConfigHolder.java:142) ~[wynntils-0.0.3-SNAPSHOT-fabric+MC-1.19.4.jar:?]
	at com.wynntils.core.config.ConfigHolder.reset(ConfigHolder.java:169) ~[wynntils-0.0.3-SNAPSHOT-fabric+MC-1.19.4.jar:?]
	at com.wynntils.core.config.ConfigManager.loadConfigOptions(ConfigManager.java:142) ~[wynntils-0.0.3-SNAPSHOT-fabric+MC-1.19.4.jar:?]
	at com.wynntils.core.config.ConfigManager.reloadConfiguration(ConfigManager.java:100) ~[wynntils-0.0.3-SNAPSHOT-fabric+MC-1.19.4.jar:?]
	at com.wynntils.core.config.ConfigManager.init(ConfigManager.java:70) ~[wynntils-0.0.3-SNAPSHOT-fabric+MC-1.19.4.jar:?]
	at com.wynntils.core.WynntilsMod.initFeatures(WynntilsMod.java:234) ~[wynntils-0.0.3-SNAPSHOT-fabric+MC-1.19.4.jar:?]
	at com.wynntils.core.WynntilsMod.onResourcesFinishedLoading(WynntilsMod.java:164) ~[wynntils-0.0.3-SNAPSHOT-fabric+MC-1.19.4.jar:?]
	at net.minecraft.class_6360.handler$bbb000$wynntils$onResourceManagerReloadPost(class_6360.java:520) ~[client-intermediary.jar:?]
	at net.minecraft.class_6360.method_36562(class_6360.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_29338(class_310.java:664) ~[client-intermediary.jar:?]
	at net.minecraft.class_156.method_17974(class_156.java:514) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_24040(class_310.java:660) ~[client-intermediary.jar:?]
	at net.minecraft.class_425.method_25394(class_425.java:147) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:926) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1218) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[minecraft-1.19.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
```

### PR DESCRIPTION
**Pull request by ryanzhoudev**
Rich presence disables itself. Also fixed the config book not updating the Enabled/Disabled button when code disables a feature. Closes #1917

### CODE REVIEW

File: common/src/main/java/com/wynntils/core/consumers/features/FeatureManager.java [hunk 1]
```diff
@@ -452,6 +454,12 @@ public void disableFeature(Feature feature) {
         Managers.Overlay.disableOverlays(feature);
 
         Managers.KeyBind.disableFeatureKeyBinds(feature);
+
+        if (McUtils.mc().screen instanceof WynntilsBookSettingsScreen settingsScreen) {
```
Comment (magicus) [inline common/src/main/java/com/wynntils/core/consumers/features/FeatureManager.java]: This logic does not belong here. You can tell the screen that it might need to do an update, like this:
`settingScreen.onFeatureUpdated(feature)`
or something like that. And then the screen will need to make sure the button is in the correct state.

File: common/src/main/java/com/wynntils/core/consumers/features/FeatureManager.java [hunk 2]
```diff
@@ -452,6 +454,12 @@ public void disableFeature(Feature feature) {
...
+            ConfigTile configTile = settingsScreen.getConfigurableStateButton(feature);
+            if (configTile == null) return;
+            configTile.getConfigOptionElement().onClick(0, 0);
```
Comment (magicus) [inline common/src/main/java/com/wynntils/core/consumers/features/FeatureManager.java]: Also, this looks fragile, assuming that you will always toggle, and faking a click. It is better to propagate the request to make sure the tile refreshes its state.

Comment (magicus) [reply common/src/main/java/com/wynntils/core/consumers/features/FeatureManager.java]: In fact; this fix will probably overshadow the discord one. So it's probably better that you separate this into two PRs.

**Review by magicus — CHANGES_REQUESTED** [review]

File: common/src/main/resources/assets/wynntils/lang/en_us.json [hunk 3]
```diff
@@ -1818,6 +1818,7 @@
   "screens.wynntils.wynntilsQuestBook.showMiniQuests.name": "Show Mini Quests",
   "screens.wynntils.wynntilsQuestBook.showQuests.name": "Show Quests",
   "screens.wynntils.wynntilsQuestBook.tryReload": "No quests found! Try reloading quests by pressing the button in the top right corner.",
+  "service.wynntils.discord.failedToLoadSDK": "Failed to load Discord SDK.",
```
Comment (magicus) [inline common/src/main/resources/assets/wynntils/lang/en_us.json]:
```suggestion
  "service.wynntils.discord.failedToLoadSDK": "Failed to load Discord SDK",
```

File: common/src/main/java/com/wynntils/services/discord/DiscordService.java [hunk 4]
```diff
@@ -31,11 +32,20 @@ public DiscordService() {
...
 
-    public void load() {
-        DiscordGameSDKCore.loadLibrary();
+    public boolean load() {
+        try {
+            DiscordGameSDKCore.loadLibrary();
+        } catch (UnsatisfiedLinkError e) {
+            if (McUtils.player() != null) {
+                McUtils.sendErrorToClient(I18n.get("service.wynntils.discord.failedToLoadSDK"));
+            }
```
Comment (magicus) [inline common/src/main/java/com/wynntils/services/discord/DiscordService.java]:
```suggestion
            McUtils.sendErrorToClient(I18n.get("service.wynntils.discord.failedToLoadSDK"));
```

This check is built-in in sendErrorToClient.

**Review by magicus — APPROVED** [review]

**Comment by magicus** [comment]
@DonkeyBlaster Will you open a separate PR for the content book updating?

**Comment by ryanzhoudev** [comment]
Yeah.
