### PR TITLE
ScoreboardManager+ObjectiveManager: Fix parsing

### LINKED ISSUE #235: ObjectiveOverlay fails to realize completion of objective
image

Likely a parsing error.

### LINKED ISSUE #259: Somebody ated the space on the scoreboard??
image
Who ated the space?? 🤔 🤯  it is a mystery...

### PR DESCRIPTION
**Pull request by kristofbolyai**
I admit this is a bit more heavy handed approach, but this seems to work fine every use case. 

Should fix #259, #235. (In #235, some objectives are just resent as completed by Wynncraft, I have seen this in legacy. /class or rejoin will fix this on Wynn's side. ObjectiveManager will now handle this at parsing.)

### CODE REVIEW

File: common/src/main/java/com/wynntils/wc/utils/scoreboard/objectives/ObjectiveManager.java [hunk 1]
```diff
@@ -83,7 +83,9 @@ public static List<WynnObjective> getObjectives() {
 
     @Override
     public void onSegmentChange(Segment newValue, ScoreboardManager.SegmentType segmentType) {
-        List<WynnObjective> objectives = reparseObjectives(newValue);
+        List<WynnObjective> objectives = reparseObjectives(newValue).stream()
+                .filter(wynnObjective -> wynnObjective.getScore() != wynnObjective.getMaxScore())
```
Comment (magicus) [inline common/src/main/java/com/wynntils/wc/utils/scoreboard/objectives/ObjectiveManager.java]:
```suggestion
                .filter(wynnObjective -> wynnObjective.getScore() < wynnObjective.getMaxScore())
```
would be clearer I think

File: common/src/main/java/com/wynntils/wc/utils/scoreboard/ScoreboardManager.java [hunk 2]
```diff
@@ -67,30 +68,37 @@ public final class ScoreboardManager {
...
+            ScoreboardLineChange processed = queueCopy.pop();
 
             if (processed.method() == ServerScoreboard.Method.REMOVE) {
+                for (ScoreboardLine lineToRemove : scoreboardLineMap.values().stream()
+                        .filter(scoreboardLine -> Objects.equals(scoreboardLine.line(), processed.lineText()))
+                        .toList()) {
+                    scoreboardLineMap.remove(lineToRemove.index());
+                }
                 continue;
             }
```
Comment (magicus) [inline common/src/main/java/com/wynntils/wc/utils/scoreboard/ScoreboardManager.java:93]: how about removing continue and making this into a proper else part? I think it would make it clearer -- if we're removing, do one thing, otherwise add/update the content.

File: common/src/main/java/com/wynntils/wc/utils/scoreboard/ScoreboardManager.java [hunk 3]
```diff
@@ -67,30 +68,37 @@ public final class ScoreboardManager {
...
         }
 
         Set<String> changedLines = new HashSet<>();
-        while (!queuedChanges.isEmpty()) {
-            ScoreboardLineChange processed = queuedChanges.pop();
+        while (!queueCopy.isEmpty()) {
+            ScoreboardLineChange processed = queueCopy.pop();
 
             if (processed.method() == ServerScoreboard.Method.REMOVE) {
+                for (ScoreboardLine lineToRemove : scoreboardLineMap.values().stream()
```
Comment (magicus) [inline common/src/main/java/com/wynntils/wc/utils/scoreboard/ScoreboardManager.java:84]: Also, this could be lambdas all way, right? Skip the for and toList and to the remove in a forEach() instead.

Comment (kristofbolyai) [reply common/src/main/java/com/wynntils/wc/utils/scoreboard/ScoreboardManager.java:84]: forEach does not work there for some reason. It is 2 am so I am either insane or I am missing something (It also didn't work now and before commiting this). For should be fine \:).

Comment (magicus) [reply common/src/main/java/com/wynntils/wc/utils/scoreboard/ScoreboardManager.java:84]: That's odd. It looks like it should work just fine. But ok, send it in as-is, and I can play around with it later.

**Review by magicus — APPROVED** [review]

**Comment by kristofbolyai** [comment]
Build seem to be broken. Github :crab:

**Comment by kristofbolyai** [comment]
Oh it is not.

**Comment by kristofbolyai** [comment]
Ah, it is.
