### PR TITLE
Maps: Fix waypoint rendering

### LINKED ISSUE #479: Jumping makes waypoint flicker

### PR DESCRIPTION
**Pull request by kristofbolyai**
Fixes #479

### CODE REVIEW

File: common/src/main/java/com/wynntils/gui/render/MapRenderer.java [hunk 1]
```diff
@@ -335,7 +334,7 @@ public static void renderTexturedPoi(
                 renderablePoi.getIcon().resource(),
                 renderX,
                 renderZ,
-                renderablePoi.getLocation().getY(),
+                0,
```
Comment (Incompleteusern) [inline common/src/main/java/com/wynntils/gui/render/MapRenderer.java:337]: What was the original purpose, and how does jumping break things?

Comment (kristofbolyai) [reply common/src/main/java/com/wynntils/gui/render/MapRenderer.java:337]: No idea, and this is not needed as we sort the waypoint rendering beforehand.

**Review by magicus — APPROVED** [review]
