### PR TITLE
feat: Chat Reborn - fix chat tabs and NPC dialogues properly

### LINKED ISSUE #2914: Duplicate messages filtered out when in NPC dialogue
What version of the mod are you using? Please include a full version number.
v2.3.9

What mod loader did you use?
Fabric

Did you use any other mods?
No

What operating system are you using?
Windows

What did you do?
Spam a few messages that were exact matches while in an NPC dialogue

What did you expect to see?
All the messages

What did you see instead?
One message

### LINKED ISSUE #3167: Certain messages are incorrectly identified as NPC dialogue
Image

I believe this was introduced with https://github.com/Wynntils/Wynntils/pull/2687

### LINKED ISSUE #3377: NPC Dialogue parsing causes non NPC dialogue to be split into multiple messages
Disabled:
`[17:51:20] [Render thread/INFO] (Minecraft) [System] [CHAT] 󏿼󐀆 ShadowCat: \n󏿼󐀆 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa \n󏿼󐀆 some long message to go onto another \n󏿼󐀆 line`

Enabled:
`[17:51:58] [Render thread/INFO] (Minecraft) [System] [CHAT] 󏿼󐀆 ShadowCat: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`
`[17:51:58] [Render thread/INFO] (Minecraft) [System] [CHAT] 󏿼󐀆 some long message to go onto another line`

Issue is created in

https://github.com/Wynntils/Wynntils/blob/0f1eddbd3698b785b5616a203008ae1c0f285e82/common/src/main/java/com/wynntils/utils/mc/StyledTextUtils.java#L74-L94

This is currently happening on the 2.1.3 beta, we will see if it resumes on the full release later today

### PR DESCRIPTION
**Pull request by magicus**
To properly fix all chat-related issues, several different things needs to be fixed. I thought I was going to be able to push them one by one, but it is difficult to not introduce regressions while part way along this route. So instead I intend to collect all changes here, but I'll merge them in as separate PRs so the reasoning will be easier to follow, and the code will be easier to review.

I start by basing this of #3554, since fixing the chat tab is the basis for all further work.

### CODE REVIEW

File: common/src/main/java/com/wynntils/handlers/chat/ChatPageDetector.java [hunk 1]
```diff
@@ -0,0 +1,497 @@
...
+                .flatMap(this::splitIntoLines)
+                .toList();
+        List<StyledText> compareLines = messageList.subList(startIndex, startIndex + 4).stream()
+                .flatMap(this::splitIntoLines)
+                .toList();
+        int numReferenceLines = referenceLines.size();
+
+        // Try to find a matching segment allowing for up to MAX_LINE_DIFFING_LINES lines difference
+        // at the beginning and end
+        int minRequiredMatches = numReferenceLines - 2 * MAX_DIFFING_LINES;
```
[the remark this answers is not in the document]
Comment (magicus) [reply common/src/main/java/com/wynntils/handlers/chat/ChatPageDetector.java]: Yeah, sure AI. :)

**Comment by magicus** [comment]
The copilot stuff is because I requested it, just to see what it could do. I'm not super impressed, but it was not entirely unhelpful either.

File: common/src/main/java/com/wynntils/services/chat/ChatTabService.java [hunk 2]
```diff
@@ -57,142 +56,176 @@ public int getTabCount() {
...
     }
 
-    public void refocusFirstTab() {
-        if (!isTabListEmpty()) {
-            setFocusedTab(0);
+    public void setFocusedTab(ChatTab focused) {
+        focusedTab = focused;
+
+        tabDataMap.get(focused).setUnreadMessages(false);
+        wrappingChatComponent.setCurrentChatComponent(getChatComponent(focused));
```
[the remark this answers is not in the document]
Comment (magicus) [reply common/src/main/java/com/wynntils/services/chat/ChatTabService.java]: It is never null.

File: common/src/main/java/com/wynntils/core/text/StyledTextPart.java [hunk 3]
```diff
@@ -119,12 +128,52 @@ static List<StyledTextPart> fromCodedString(String codedString, Style style, Sty
...
+            }
 
-                currentStyle = currentStyle.applyFormat(formatting);
+            if (specialPrefix) {
+                if (current != '}') {
+                    // Keep appending until we find the closing bracket
+                    specialString.append(current);
+                    continue;
+                } else {
+                    // We currently do not have any special formatting
```
Comment (magicus) [inline common/src/main/java/com/wynntils/core/text/StyledTextPart.java:143]: @kristofbolyai This is the piece of code I am least proud of in this PR. It's basically just code duplication. I think there is no way to skip this, other than to design this function, but at least I wanted to check it with you.

I think we can refactor the function, but I'm not really keen on doing that, at least not know, and ideally I think you should do it who are more knowledgeable in the details of StyledText.

**Comment by magicus** [comment]
I think this is done now. I will try to do some extensive real-world game play testing with this branch today. But if I see no issues I think we should integrate this and make a new release. There are so many benefits with this branch. Chat tabs work properly, especially if you enable/disable them (history will no longer be lost). NPC dialogues work properly. And if you have NPC dialogues enabled, messages sent in background color will now be properly replaced by the real foreground color as soon as Wynn sends them out to us (when the dialogue is finished). And multi-line messages that are not NPC dialogues work properly for detection.

File: common/src/main/java/com/wynntils/core/text/StyledTextPart.java (hunk 3 above)
Comment (kristofbolyai) [reply common/src/main/java/com/wynntils/core/text/StyledTextPart.java:143]: I will try to check it out on desktop on the weekend, although this is definitely not a blocker for this featureset IMO.

**Comment by ShadowCat117** [comment]
I'll try this out for a few hours too, if we can get this and the gear sharing in today that would be ideal as then we'll have all of tomorrow to solve any issues

**Comment by ShadowCat117** [comment]
haven't been able to reliably find repro steps, but with chat tabs and npc dialogue enabled, I keep getting into a state where I recieve no chat messages and have to reselect the "All" tab to see everything.

Also, the trade market auto open chat is still broken

**Comment by ShadowCat117** [comment]
Actually I think I've got it, it happens after I save my settings so presumably an onConfigUpdate somewhere is resetting the focus tab maybe?

Potentially related, getting this on launch despite having chat tabs setup
`Cannot enable Chat Tabs: no tabs configured`

**Comment by ShadowCat117** [comment]
With NPC Dialogue overlay off and Chat Display Type set to normal in the feature, NPC dialogue messages aren't being removed from chat after they are finished
image

**Comment by ShadowCat117** [comment]
Unfortunately it's not easy to redo as it's a level 73 quest, but I remember last time NPC dialogue was worked on we used the Hollow Serenity quest to check some multi choice dialogue and I just tried it with this.

Even after selecting the final option I have this permanently on my screen until I change world

image

And my entire chat history was resent after selecting the 4th option, it didn't get filtered out.

It might just be an issue unique to this quest where it uses a slightly different system and when it eventually gets remade it might be fixed then. The other quest I think has issues is The Hero of Gavel but I don't think I have any characters with that quest unlocked

**Comment by ShadowCat117** [comment]
Same quest, a later multi dialogue option isn't being detected
image

File: common/src/main/java/com/wynntils/handlers/chat/ChatPageDetector.java [hunk 4]
```diff
@@ -0,0 +1,497 @@
...
+
+        int lineCount = StyledTextUtils.getLineCount(styledText);
+        synchronized (this) {
+            if (pageFinishedTask == null) {
+                // Normal single line chat messages will just be passed through
+                if (lineCount == 1) return false;
+
+                // Wait a reasonable amount of time for all messages in the page to arrive
+                pageFinishedTask = TaskUtils.schedule(
+                        this::onPotentialPageFinished, NORMAL_PAGE_WAIT, java.util.concurrent.TimeUnit.MILLISECONDS);
```
Comment (ShadowCat117) [inline common/src/main/java/com/wynntils/handlers/chat/ChatPageDetector.java]: Something happened here, can just import that

File: common/src/main/java/com/wynntils/handlers/chat/ChatPageDetector.java [hunk 5]
```diff
@@ -0,0 +1,497 @@
...
+import java.util.Deque;
+import java.util.LinkedList;
+import java.util.List;
+import java.util.concurrent.Future;
+import java.util.stream.Stream;
+import net.minecraft.client.GuiMessage;
+import net.minecraft.client.gui.components.ChatComponent;
+import net.minecraft.network.chat.Component;
+
+public final class ChatPageDetector {
```
Comment (ShadowCat117) [inline common/src/main/java/com/wynntils/handlers/chat/ChatPageDetector.java:27]: Seen a lot of the magic number 4 in this class, maybe make it a constant

**Review by ShadowCat117 — COMMENTED** [review]
Besides my comments for the issues I found this looks good

File: common/src/main/java/com/wynntils/core/text/StyledTextPart.java (hunk 3 above)
Comment (kristofbolyai) [reply common/src/main/java/com/wynntils/core/text/StyledTextPart.java:143]: Yes, this code is definitely something we can get rid of. However, I would maybe wait until we have more special formattings, we don't know the scope of this fully so keeping this a bit more open ended would make sense.

**Comment by kristofbolyai** [comment]
As pointed out by ShadowCat, there is still a bit of work left. I don't see anything outstanding in the code that I can comment on. I will try to do a new round of review when behavior is finalized.

**Comment by ShadowCat117** [comment]
One final issue I've noticed, it seems like when your name is mentioned in dialogue (I haven't tested this in non overlay mode but I assume it is the same) it appears white instead of green. This is likely only when you have a nickname but I will double check.

image

I'm pretty sure your name is mentioned in the tutorial so at least that one is easy to repeat, just make sure you set a nickname before doing it.

Update: Yes, it is just with a nickname
image

**Comment by magicus** [comment]
> One final issue I've noticed, it seems like when your name is mentioned in dialogue (I haven't tested this in non overlay mode but I assume it is the same) it appears white instead of green. 

I've noticed that as well, but think that is how Wynn sends out the text? I believe it is the same without NPC separation?

File: common/src/main/java/com/wynntils/core/text/StyledTextPart.java (hunk 3 above)
Comment (magicus) [reply common/src/main/java/com/wynntils/core/text/StyledTextPart.java:143]: So if I understand you right, this is okay for now?

**Comment by ShadowCat117** [comment]
> I've noticed that as well, but think that is how Wynn sends out the text? I believe it is the same without NPC separation?

Later on in the quest, my name was mentioned earlier and all following text was also white, I don't remember if it was italicised too but either way I don't think Wynn would send it all as white

**Comment by magicus** [comment]
Summarizing things to fix:

* [x] Ending up in a state where you have to reselect "All" tab to see anything. Happens after saving settings, onConfigUpdate resetting the focused tab?
* [x] On launch getting in log: `Cannot enable Chat Tabs: no tabs configured`
* [x] Trade market auto open chat is broken
* [x] Break out magic number of 4 components for page background
* [x] Look into weird white formatting for nicknames in dialogue text
* [x] With NPC Dialogue overlay off and Chat Display Type set to normal in the feature, NPC dialogue messages aren't being removed from chat after they are finished
* [ ] End of Dialogue was not properly detected in one dialogue in the "Hollow Serenity" quest
* [ ] One selection dialogue was not detected in the "Hollow Serenity" quest

File: common/src/main/java/com/wynntils/handlers/chat/ChatPageDetector.java (hunk 4 above)
Comment (magicus) [reply common/src/main/java/com/wynntils/handlers/chat/ChatPageDetector.java]: I think what happened was too much tooling support and too little attention :)

**Comment by magicus** [comment]
wynn-moment

As I thought, the "formatting is all white after a nickname" problem is a Wynn problem. This is without chat tabs and NPC dialogues.

**Comment by ShadowCat117** [comment]
Ah yes, just tried vanilla 1.21.4 and it is indeed white. Time for a bug report I suppose :)

**Comment by magicus** [comment]
>  With NPC Dialogue overlay off and Chat Display Type set to normal in the feature, NPC dialogue messages aren't being removed from chat after they are finished

Actually, I don't think like the "post to chat if overlay is disabled" functionality. I added it as a kind of hack, but if you want to have the messages in the chat then you should not use the NPC dialogue functionality at all. Maybe I should just remove it?

edit: I cannot reproduce this. However, when setting the type to "legacy" it does not get removed.  

edit^2: Actually, that was maybe kind of the point with "legacy".

I'm going to leave this as-is. I cannot reproduce the problem with messages not being removed. I don't like this entire idea (even though I created it), but I will not remove it now. I can't say it is any worse than the current situation anyway.

**Comment by magicus** [comment]
@ShadowCat117 Can you reproduce this with any dialogue? I've still not completed A Journey Beyond with any of my characters so I can't test in Lutho. It might be something special/buggy about that particular dialogue.

**Comment by ShadowCat117** [comment]
Happens with Detlas NPC's too
image

**Comment by ShadowCat117** [comment]
Imo the overlay disabled but non-legacy mode should replicate the vanilla Wynncraft experience but with our benefits of hiding all of the background text and auto progressing

**Comment by magicus** [comment]
> Imo the overlay disabled but non-legacy mode should replicate the vanilla Wynncraft experience but with our benefits of hiding all of the background text and auto progressing

Sure... good luck implementing that, though. :-/ I'll go talk to Sayleros and see if I can replicate.

**Comment by magicus** [comment]
No, I can't reproduce. The NPC text disappears for me after I leave the dialog. I wonder if there is some other feature interaction at play here...

edit: I removed my config file, and now I can reproduce it. I'll try to figure out what setting I had that "fixed" the problem.

**Comment by magicus** [comment]
I am just stupid. I did not have Chat Tabs enabled.
doh

**Comment by ShadowCat117** [comment]
Chat Tabs, the gift that keeps on giving issues

**Comment by magicus** [comment]
Yeah, I'm starting to think the WrappingChatComponent was not the best solution. I have one idea of a fix but it it does not work I guess it's back to the drawing board.

**Comment by magicus** [comment]
@ShadowCat117 @kristofbolyai I have fixed everything I could reproduce. My closest character is still just level 71 so a bit left until "Hollow Serenity".

I'll try playing with this a bit more. I think the problem ShadowCat spotted might not have been with the quest per se (but it can of course be), but some random event causing the page detection to fail. It is still the most brittle thing here; I've tried to cover for all weird stuff I've seen but there can probably be some other strange things happening.

**Comment by magicus** [comment]
I've play tested this quite extensively with both tabs and NPC dialogue, running different quests, and not seeing any issues. I think this is ready to integrate.

**Comment by ShadowCat117** [comment]
Just did a quick test and can confirm my previously reported issues are fixed, it also seems like this fixes https://github.com/Wynntils/Wynntils/issues/2914 

I'd like to give this a bit more testing to make sure everything is good but it looks promising

**Comment by ShadowCat117** [comment]
Also, should we re-enable the feature by default? It does make the experience a lot better and if it doesn't seem to be causing any issues there's no harm

**Comment by ShadowCat117** [comment]
And maybe https://github.com/Wynntils/Wynntils/issues/3167 too? I can't get it to happen with the trade message at least

**Comment by magicus** [comment]
Yes, this will fix https://github.com/Wynntils/Wynntils/issues/3167.

**Comment by magicus** [comment]
I've thought about going through the bug list and see if there are more issues that will be fixed by this.

**Comment by magicus** [comment]
> Also, should we re-enable the feature by default? It does make the experience a lot better and if it doesn't seem to be causing any issues there's no harm

I think that's a good point. I'll do that.

**Comment by ShadowCat117** [comment]
Apparently there is an issue with the translation feature spamming chat atm, my guess is it was caused by https://github.com/Wynntils/Wynntils/pull/3549, maybe the feature is causing another chat event to be posted and it's just stuck in an infinite loop of posting chat messages. Can either fix that in this or separately

**Comment by magicus** [comment]
Let's fix that separately. This PR is large enough as it is.

File: common/src/main/java/com/wynntils/services/chat/ChatTabService.java [hunk 6]
```diff
@@ -57,142 +61,236 @@ public int getTabCount() {
...
+
+        // Pass the historic messages from the vanilla chat component to all the new tabs
+        McUtils.mc().gui.chat.allMessages.reversed().forEach(msg -> {
+            Component component = msg.content();
+            StyledText styledText = StyledText.fromComponent(component);
+            RecipientType recipientType = Handlers.Chat.getRecipientType(styledText, MessageType.FOREGROUND);
+            List<ChatTab> recipientTabs = Services.ChatTab.getRecipientTabs(recipientType, styledText);
+
+            recipientTabs.forEach(tab -> Services.ChatTab.getChatComponent(tab).addMessage(component));
+        });
```
[the remark this answers is not in the document]
Comment (ShadowCat117) [reply common/src/main/java/com/wynntils/services/chat/ChatTabService.java:155]: I like how it sets the limit to 100 when that is the vanilla chat limit

File: common/src/main/java/com/wynntils/handlers/chat/ChatPageDetector.java [hunk 7]
```diff
@@ -0,0 +1,492 @@
...
+        List<StyledText> referenceLines =
+                messageList.subList(oldPageIndex, oldPageIndex + PAGE_BACKGROUND_MESSAGES).stream()
+                        .flatMap(this::splitIntoLines)
+                        .toList();
+        List<StyledText> compareLines = messageList.subList(startIndex, startIndex + PAGE_BACKGROUND_MESSAGES).stream()
+                .flatMap(this::splitIntoLines)
+                .toList();
+        int numReferenceLines = referenceLines.size();
+
+        // Try to find a matching segment allowing for up to MAX_LINE_DIFFING_LINES lines difference
```
[the remark this answers is not in the document]
Comment (ShadowCat117) [reply common/src/main/java/com/wynntils/handlers/chat/ChatPageDetector.java]: It really wants you to rename this 😅

**Review by ShadowCat117 — APPROVED** [review]
I think this looks good to go! Thanks for doing this, chat related things are one of my least favourite to work on so glad someone else was able to take up this task :)

**Comment by ShadowCat117** [comment]
Do you want to do a release for this today or tomorrow? I might work from home tomorrow so will be around if a revert or fix is needed

**Comment by magicus** [comment]
I don't have any opinion. I don't think it will crash so badly we will need to revert it, but should that be we just have to check in an anti-delta. If there are minor issues I'll tackle them when I get the time. But I think this is ready and there is really no reason to delay any further in releasing it.

**Comment by ShadowCat117** [comment]
Ok, I think I'll release somepoint tomorrow then along with the Hades fix

**Comment by magicus** [comment]
I've tested this even more. At one occasion, we failed to detect the page mode properly, and the dialogue, including a repeat of the entire screen, stayed on the overlay. I've pushed a fix that will allow us to detect if this happens and at least remove the overlay. If that ever happens to a player, it will be a bit annoying but then at least it will be resolved as soon as a new chat message arrives. If I am ever able to catch in the debugger what is happening in these cases, I might be able to make the algorithm more robust. But I have probably tested thousands and thousands of chat pages, and only seen a single mistaken case, so the success rate is above 99.99% and I think that's fair.

**Comment by ShadowCat117** [comment]
One final issue actually and then I think we can merge, we need to send the multi choice dialogue in chat if there are more than 9 options, the silverbull beacon expert will always give 14 options

image

**Comment by magicus** [comment]
I see. I'll fix.

**Comment by magicus** [comment]
Do not integrate yet. Somewhere along the line, I broke the no overlay but NPC dialogue separation functionality. :(

Edit: Fixed.

**Comment by ShadowCat117** [comment]
I'll give this one final check in a few hours. Had an idea that we could save for later. If the selection has more than 9 options, maybe we could paginate it so 1-8 will be as normal but 9 will be go to the next page where you'll see the 9-? options, maybe 1 would be to return to the previous page in this scenario

**Comment by magicus** [comment]
I think we let the option selection be like this for now. My long-term thinking is that we should make a screen with selection buttons you can click on, and then you can have any number of buttons.
