### PR TITLE
KeyBindManager: Make mouse keybinds work in inventories

### LINKED ISSUE #333: Using mouse buttons as keybinds doesn't work in inventories
image
In the screenshot I've set a spare mouse button to select items to compare. But this doesn't work.

### PR DESCRIPTION
**Pull request by kristofbolyai**
Fixes #333.

### CODE REVIEW

File: common/src/main/resources/wynntils.accessWidener [hunk 1]
```diff
@@ -17,3 +17,4 @@ accessible field net/minecraft/world/scores/Scoreboard displayObjectives [Lnet/m
 accessible field net/minecraft/world/scores/Scoreboard playerScores Ljava/util/Map;
 mutable field net/minecraft/world/scores/Scoreboard playerScores Ljava/util/Map;
 accessible method net/minecraft/client/gui/screens/Screen renderTooltip (Lcom/mojang/blaze3d/vertex/PoseStack;Lnet/minecraft/world/item/ItemStack;II)V
+accessible field net/minecraft/client/KeyMapping key Lcom/mojang/blaze3d/platform/InputConstants$Key;
```
Comment (magicus) [inline common/src/main/resources/wynntils.accessWidener]: Missing line break at EOF

File: common/src/main/java/com/wynntils/core/keybinds/KeyBindManager.java [hunk 2]
```diff
@@ -38,6 +39,15 @@ public static void onKeyPress(InventoryKeyPressEvent e) {
         });
     }
 
+    @SubscribeEvent
+    public static void onMousePress(InventoryMouseClickedEvent e) {
+        KEY_BINDS.forEach(keyBind -> {
+            if (keyBind.getKeyMapping().key.getValue() == e.getButton()) {
```
Comment (magicus) [inline common/src/main/java/com/wynntils/core/keybinds/KeyBindManager.java]: I think you can use `matchesMouse()` instead. Also means you don't have to expose `key`.

**Review by magicus — APPROVED** [review]
