### PR TITLE
fix: Fix certain ingredients using API name not being annotated [skip ci]

### LINKED ISSUE #2836: The return value of pouch_free is not reduced when a particular Ingredient occupies an Ingredient Pouch
Slots in the Ingredient Pouch occupied by Toxxulous Ripper's Leg are not reflected in the `pouch_free` function.
For example, if all slots in the Ingredient Pouch are filled with this Ingredient, the value of `pouch_free` will still be 27.

- Wynntils version: 2.1.1
- Mod loader: fabric-loader-0.16.2-1.21.1
- Other mods: None
- Operating system: Windows 10

### PR DESCRIPTION
**Pull request by ShadowCat117**
Fixes #2836

image

The specific ingredient mentioned in the issue uses `’` in the name in-game whereas all others with an apostrophe use `'`

### CODE REVIEW

File: common/src/main/java/com/wynntils/models/items/annotators/gui/IngredientPouchAnnotator.java [hunk 1]
```diff
@@ -44,7 +44,10 @@ public ItemAnnotation getAnnotation(ItemStack itemStack, StyledText name) {
             IngredientInfo ingredientInfo = Models.Ingredient.getIngredientInfoFromName(ingredientName);
 
             // Skip unknown ingredients; the pouch list will be wrong but better than nothing
```
Comment (magicus) [inline common/src/main/java/com/wynntils/models/items/annotators/gui/IngredientPouchAnnotator.java]: This comments need to move to above line 49 now.

**Review by magicus — APPROVED** [review]

**Comment by kristofbolyai** [comment]
That's so annoying. I'll bother create a thread about this in the API Discord.
