### PR TITLE
fix: Sync player ranks and related features to 2.0.3

### LINKED ISSUE #1748: [2.0.3] Login redirect is broken, needs new patterns

### PR DESCRIPTION
**Pull request by ryanzhoudev**
Closes #1748
image

Tested with all normal store-obtainable ranks. Couldn't check any ct/staff ranks.

### CODE REVIEW

File: common/src/main/java/com/wynntils/models/players/type/PlayerRank.java [hunk 1]
```diff
@@ -7,24 +7,36 @@
...
+    char web = '\uE025';
 
+    String teststring = "\uE014 \uE015 \uE016 \uE017 \uE018 \uE019 \uE01A \uE01B \uE01C \uE01D \uE01E \uE01F \uE020 \uE021 \uE022 \uE023 \uE024 \uE025";
     private final String tag;
+    private final char newTag;
     private final ChatFormatting primaryColor;
     private final ChatFormatting secondaryColor;
 
-    PlayerRank(String tag, ChatFormatting primaryColor, ChatFormatting secondaryColor) {
+    PlayerRank(String tag, char newTag, ChatFormatting primaryColor, ChatFormatting secondaryColor) {
```
Comment (Mcrtin) [inline common/src/main/java/com/wynntils/models/players/type/PlayerRank.java]: can you rename this to `unicodeTag`

Comment (kristofbolyai) [reply common/src/main/java/com/wynntils/models/players/type/PlayerRank.java]: Should be `String name, char tag` but this is an early draft so no point in bugging in it. This PR's purpose is that others don't work on it.

File: common/src/main/java/com/wynntils/models/players/type/PlayerRank.java [hunk 2]
```diff
@@ -7,51 +7,64 @@
...
-        this.primaryColor = primaryColor;
-        this.secondaryColor = secondaryColor;
+        this.textColor = textColor;
+        this.accentColor = accentColor;
     }
 
     public static PlayerRank fromString(String rankString) {
         for (PlayerRank rank : values()) {
-            if (rank.tag.equals(rankString)) {
+            if (rank.name.equals(rankString) || rank.tag.equals(rankString)) {
```
Comment (ryanzhoudev) [inline common/src/main/java/com/wynntils/models/players/type/PlayerRank.java:47]: This might seem a bit odd to keep the name.equals but I plan to parse with it later, either in the silverbull menu or the info menu, then we can have accurate party sizes in discord rpc

Comment (kristofbolyai) [reply common/src/main/java/com/wynntils/models/players/type/PlayerRank.java:47]: sounds good

File: common/src/main/java/com/wynntils/features/redirects/ChatRedirectFeature.java [hunk 3]
```diff
@@ -503,10 +505,13 @@ protected StyledText getNotification(Matcher matcher) {
...
+        // Test suite: https://regexr.com/7jhti
+        private static final String RANK_STRING =
+                Arrays.stream(PlayerRank.values()).map(PlayerRank::getTag).collect(Collectors.joining());
         private static final Pattern FOREGROUND_PATTERN = Pattern.compile(
-                "^§.\\[(§.)+\\|?(§.)*(?<rank>[a-zA-Z+]+)(§.)+\\|?(§.)*\\] §.(?<name>.*)§. has just logged in!$");
-        private static final Pattern BACKGROUND_PATTERN = Pattern.compile(
-                "^(?:§8)?\\[(§.)+\\|?(§.)*(?<rank>[a-zA-Z+]+)(§.)+\\|?(§.)*\\] §7(?<name>.*)§8 has just logged in!$");
+                "^(?<rank>[" + RANK_STRING + "]) §#[0-9a-f]{5}(?<name>[\\w ]{1,20})§[0-9a-f] has just logged in!$");
+        private static final Pattern BACKGROUND_PATTERN = Pattern.compile("^(?:§8)?\\[(§.)+\\|?(§.)*(?<rank>["
+                + RANK_STRING + "]) §#[0-9a-f]{5}(?<name>[\\\\w ]{1,20})§[0-9a-f] has just logged in!$");
```
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/features/redirects/ChatRedirectFeature.java]: `§#[0-9a-f]{5}`?

Comment (kristofbolyai) [reply common/src/main/java/com/wynntils/features/redirects/ChatRedirectFeature.java]: I double don't understand this? 5 chars? Not 6/8? I know we use `§#` in StyledText to represent colors outside of the ChatFormatting range. But I am not sure what this is..

Comment (ryanzhoudev) [reply common/src/main/java/com/wynntils/features/redirects/ChatRedirectFeature.java]: Yeah I dunno either. This is what I get from chat.
`[03:40:50] [Render thread/INFO]: [CHAT]  &#fe600v8j&6 has just logged in!`

File: common/src/main/java/com/wynntils/features/redirects/ChatRedirectFeature.java [hunk 4]
```diff
@@ -503,10 +505,13 @@ protected StyledText getNotification(Matcher matcher) {
...
+        // Test suite: https://regexr.com/7jhti
+        private static final String RANK_STRING =
+                Arrays.stream(PlayerRank.values()).map(PlayerRank::getTag).collect(Collectors.joining());
         private static final Pattern FOREGROUND_PATTERN = Pattern.compile(
-                "^§.\\[(§.)+\\|?(§.)*(?<rank>[a-zA-Z+]+)(§.)+\\|?(§.)*\\] §.(?<name>.*)§. has just logged in!$");
-        private static final Pattern BACKGROUND_PATTERN = Pattern.compile(
-                "^(?:§8)?\\[(§.)+\\|?(§.)*(?<rank>[a-zA-Z+]+)(§.)+\\|?(§.)*\\] §7(?<name>.*)§8 has just logged in!$");
+                "^(?<rank>[" + RANK_STRING + "]) §#[0-9a-f]{8}(?<name>[\\w ]{1,20})§[0-9a-f] has just logged in!$");
+        private static final Pattern BACKGROUND_PATTERN = Pattern.compile("^(?:§8)?\\[(§.)+\\|?(§.)*(?<rank>["
+                + RANK_STRING + "]) §#[0-9a-f]{8}(?<name>[\\w ]{1,20})§[0-9a-f] has just logged in!$");
```
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/features/redirects/ChatRedirectFeature.java]: `§#[0-9a-f]{6, 8}` because we don't include the alpha every case (this might work but 6, 8 is a bit more comaptible)

File: common/src/main/java/com/wynntils/features/redirects/ChatRedirectFeature.java [hunk 5]
```diff
@@ -503,10 +505,13 @@ protected StyledText getNotification(Matcher matcher) {
...
 
     private class LoginRedirector extends SimpleRedirector {
+        // Test suite: https://regexr.com/7jhti
+        private static final String RANK_STRING =
+                Arrays.stream(PlayerRank.values()).map(PlayerRank::getTag).collect(Collectors.joining());
         private static final Pattern FOREGROUND_PATTERN = Pattern.compile(
-                "^§.\\[(§.)+\\|?(§.)*(?<rank>[a-zA-Z+]+)(§.)+\\|?(§.)*\\] §.(?<name>.*)§. has just logged in!$");
-        private static final Pattern BACKGROUND_PATTERN = Pattern.compile(
-                "^(?:§8)?\\[(§.)+\\|?(§.)*(?<rank>[a-zA-Z+]+)(§.)+\\|?(§.)*\\] §7(?<name>.*)§8 has just logged in!$");
+                "^(?<rank>[" + RANK_STRING + "]) §#[0-9a-f]{8}(?<name>[\\w ]{1,20})§[0-9a-f] has just logged in!$");
```
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/features/redirects/ChatRedirectFeature.java]:
```suggestion
                "^(?<rank>[" + RANK_STRING + "]) §#[0-9a-f]{8}(?<name>[\\w ]{1,20})§. has just logged in!$");
```

We usually don't do that whole spec, just . it.

Comment (Mcrtin) [reply common/src/main/java/com/wynntils/features/redirects/ChatRedirectFeature.java]: discoverd `\p{XDigit}` for `[0-9a-fA-F]` maybe we can use that?

Comment (kristofbolyai) [reply common/src/main/java/com/wynntils/features/redirects/ChatRedirectFeature.java]: Readability is still non existent when using that (which is the problem with the other one as well).

**Review by kristofbolyai — APPROVED** [review]
