### PR TITLE
More minimap

### LINKED ISSUE #349: Minimap suddenly appears
Since the map is loaded asynchronously, it might cause a jumpscare when wynntils starts rendering the minimap

To reproduce, delete apicache and join wynncraft before the map can be fully downloaded again.

### PR DESCRIPTION
**Pull request by Incompleteusern**
Fix
- [x] Fix #349 

New things
- [x] Cursor Color
- [x] Directional Text
- [x] Coordinate Text

image
image

### CODE REVIEW

**Comment by magicus** [comment]
Screenshot?

**Comment by Incompleteusern** [comment]
It's still in draft, so I haven't ironed out all the kinks yet.
image
Here's an old screenshot

File: common/src/main/java/com/wynntils/features/user/overlays/map/MiniMapOverlayFeature.java [hunk 1]
```diff
@@ -100,33 +109,130 @@ public void render(PoseStack poseStack, float partialTicks, Window window) {
...
+                                CommonColors.WHITE,
+                                HorizontalAlignment.Center,
+                                VerticalAlignment.Middle,
+                                FontRenderer.TextShadow.NONE);
+            }
+        }
+
+        private void renderCardinalDirections(
+                PoseStack poseStack, float width, float height, float centerX, float centerZ) {
+            if (showCompass != CompassRenderType.None) {
```
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/features/user/overlays/map/MiniMapOverlayFeature.java]: Invert if?

File: common/src/main/java/com/wynntils/features/user/overlays/map/MiniMapOverlayFeature.java [hunk 2]
```diff
@@ -100,33 +109,130 @@ public void render(PoseStack poseStack, float partialTicks, Window window) {
...
+                        northDX *= toSquareScale;
+                        northDY *= toSquareScale;
+                    }
+
+                } else {
+                    northDX = width / 2;
+                    northDY = height / 2;
+                }
+
+                FontRenderer.getInstance()
```
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/features/user/overlays/map/MiniMapOverlayFeature.java]: Perhaps a local method to de-duplicate code (and pass renderX, renderY and text)?

File: common/src/main/java/com/wynntils/mc/render/FontRenderer.java [hunk 3]
```diff
@@ -40,44 +40,42 @@ public int renderText(
...
-                        customColor,
-                        TextAlignment.LEFT_ALIGNED,
-                        shadow);
-            case RIGHT_ALIGNED:
-                return renderText(
-                        poseStack, text, x - font.width(text), y, customColor, TextAlignment.LEFT_ALIGNED, shadow);
+        renderX = switch (horizontalAlignment) {
+            case Left -> x;
+            case Center -> x - font.width(text) / 2.0f;
+            case Right -> x - font.width(text);};
```
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/mc/render/FontRenderer.java:56]: How did spotless allow this?

File: common/src/main/java/com/wynntils/mc/render/FontRenderer.java [hunk 4]
```diff
@@ -40,44 +40,42 @@ public int renderText(
             float x,
             float y,
             CustomColor customColor,
-            TextAlignment alignment,
+            HorizontalAlignment horizontalAlignment,
```
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/mc/render/FontRenderer.java:43]: There is already `FontRenderer#renderAlignedTextInBox` (although y alignment is only in #345)

File: common/src/main/java/com/wynntils/features/user/overlays/map/MiniMapOverlayFeature.java [hunk 5]
```diff
@@ -59,6 +65,12 @@ public static class MiniMapOverlay extends Overlay {
         @Config
         public PointerType pointerType = PointerType.Arrow;
 
+        @Config
+        public CompassRenderType showCompass = CompassRenderType.All;
+
+        @Config
+        public boolean showCoords = true;
```
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/features/user/overlays/map/MiniMapOverlayFeature.java:73]: Missing I18n

File: common/src/main/java/com/wynntils/features/user/overlays/map/MiniMapOverlayFeature.java [hunk 6]
```diff
@@ -50,6 +53,9 @@ public static class MiniMapOverlay extends Overlay {
         @Config
         public boolean renderUsingLinear = true;
 
+        @Config
+        public CustomColor cursorColor = new CustomColor(1f, 1f, 1f, 1f);
```
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/features/user/overlays/map/MiniMapOverlayFeature.java]: Missing I18n. (If you delete your run configs in `.idea/runConfigurations` and reload the gradle project, you will have assertions enabled in dev env, not allowing missing I18n)

**Review by kristofbolyai — COMMENTED** [review]
I pointed out a few things, I know this is WIP though. 

I like the removal of TextAlignment, but, I hope you checked most overlays that it does indeed still work. As for the changed method, I am not sure we will need that.

File: common/src/main/java/com/wynntils/mc/render/FontRenderer.java (hunk 3 above)
Comment (Incompleteusern) [reply common/src/main/java/com/wynntils/mc/render/FontRenderer.java:56]: I do not know

File: common/src/main/java/com/wynntils/features/user/overlays/map/MiniMapOverlayFeature.java (hunk 1 above)
Comment (Incompleteusern) [reply common/src/main/java/com/wynntils/features/user/overlays/map/MiniMapOverlayFeature.java]: I don't understand what you are saying?

Comment (kristofbolyai) [reply common/src/main/java/com/wynntils/features/user/overlays/map/MiniMapOverlayFeature.java]: If renderType is None, return. If I see the code correctly, this would reduce right shift.

File: common/src/main/java/com/wynntils/mc/render/FontRenderer.java (hunk 4 above)
Comment (Incompleteusern) [reply common/src/main/java/com/wynntils/mc/render/FontRenderer.java:43]: Im going to try and make a `FontRenderer#renderAlignedTextInBox` for both x and y, just x, and just y

Comment (kristofbolyai) [reply common/src/main/java/com/wynntils/mc/render/FontRenderer.java:43]: Code is in the settings pr already

File: common/src/main/java/com/wynntils/features/user/overlays/map/MiniMapOverlayFeature.java (hunk 2 above)
Comment (Incompleteusern) [reply common/src/main/java/com/wynntils/features/user/overlays/map/MiniMapOverlayFeature.java]: Should be partially lowered through using a render setting now. Unresolve this issue if you think more can/should be done.

File: common/src/main/java/com/wynntils/mc/render/FontRenderer.java (hunk 4 above)
Comment (Incompleteusern) [reply common/src/main/java/com/wynntils/mc/render/FontRenderer.java:43]: > There is already `FontRenderer#renderAlignedTextInBox` (although y alignment is only in #345)

There isn't a box here.

Comment (Incompleteusern) [reply common/src/main/java/com/wynntils/mc/render/FontRenderer.java:43]: [This](https://github.com/Wynntils/Artemis/pull/377/commits/747a9b0ccf0a498bbe4790f6103b4eef1064d73f) has added a few more `FontRenderer#renderAlignedTextInBox` methods, and should have the same signature (other than textalignment being deleted) as the new one in #345

File: common/src/main/java/com/wynntils/features/user/overlays/map/MiniMapOverlayFeature.java [hunk 7]
```diff
@@ -100,33 +110,131 @@ public void render(PoseStack poseStack, float partialTicks, Window window) {
...
+                    northDX *= toSquareScaleNorth;
+                    northDY *= toSquareScaleNorth;
+                }
+            } else {
+                northDX = 0;
+                northDY = -height / 2;
             }
 
-            // TODO minimap icons
+            FontRenderer.getInstance()
```
Comment (magicus) [inline common/src/main/java/com/wynntils/features/user/overlays/map/MiniMapOverlayFeature.java:179]: For consistency, can you move the "N" rendering down to after the calculations, and group it with the other cardinal letter rendering?

Comment (magicus) [reply common/src/main/java/com/wynntils/features/user/overlays/map/MiniMapOverlayFeature.java:179]: ... and possibly fold the eastDX/DY calculation in with the northDX/DY calculation

File: common/src/main/java/com/wynntils/features/user/overlays/map/MiniMapOverlayFeature.java [hunk 8]
```diff
@@ -100,33 +110,131 @@ public void render(PoseStack poseStack, float partialTicks, Window window) {
...
+                    .renderText(
+                            poseStack,
+                            centerX + northDX,
+                            centerZ + northDY,
+                            new TextRenderTask("N", TextRenderSetting.CENTERED));
 
-            // TODO compass icon
+            if (showCompass == CompassRenderType.North) return;
```
Comment (magicus) [inline common/src/main/java/com/wynntils/features/user/overlays/map/MiniMapOverlayFeature.java:186]: Aha, I see, you provide the option to only render "N", so this way it is a slight optimization. Hm. I think readability is more important, but if you feel differently, keep it as it is.

File: common/src/main/java/com/wynntils/mc/render/FontRenderer.java (hunk 3 above)
Comment (magicus) [reply common/src/main/java/com/wynntils/mc/render/FontRenderer.java:56]: But will you fix it?

File: common/src/main/java/com/wynntils/features/user/overlays/map/MiniMapOverlayFeature.java (hunk 8 above)
Comment (Incompleteusern) [reply common/src/main/java/com/wynntils/features/user/overlays/map/MiniMapOverlayFeature.java:186]: I feel as though this is worth it overall, it kind of indicates that `eastDX` and `eastDY` only matter later

File: common/src/main/java/com/wynntils/mc/render/FontRenderer.java [hunk 9]
```diff
@@ -89,29 +126,46 @@ public void renderAlignedTextInBox(
...
-                    poseStack,
-                    text,
-                    x2 - font.width(text),
-                    y,
-                    maxWidth,
-                    customColor,
-                    TextAlignment.LEFT_ALIGNED,
-                    textShadow);
-        }
+
```
Comment (magicus) [inline common/src/main/java/com/wynntils/mc/render/FontRenderer.java]: Spotless is not really helpful here.

But, there's an extra empty line which just makes a bad line look even worse. Can you remove it? (also in the next method)

**Review by magicus — DISMISSED** [review]
This turned out to be mostly a "refactor text rendering", not a "more minimap stuff" PR. I'm not saying the refactoring was not needed; as far as I can tell it looks very nice. But it's a bit of a pity that the two concerns were mixed into one PR. If you notice that you end up doing a massive refactoring to be able to write the code that you want, do a `git stash` or something like that with your "actual" changes, and submit a separate PR first with just the refactorings.

**Comment by Incompleteusern** [comment]
> This turned out to be mostly a "refactor text rendering", not a "more minimap stuff" PR. I'm not saying the refactoring was not needed; as far as I can tell it looks very nice. But it's a bit of a pity that the two concerns were mixed into one PR. If you notice that you end up doing a massive refactoring to be able to write the code that you want, do a `git stash` or something like that with your "actual" changes, and submit a separate PR first with just the refactorings.

Originally I just wanted to be able to render in the center + middle through text alignments and was going to refactor the relevant method, but that butterflied

**Review by magicus — APPROVED** [review]
