### PR TITLE
fix: Custom connect screen does not revert on failure

### LINKED ISSUE #2128: Custom loading screen does not revert to vanilla on certain errors
#2002 for details.

### PR DESCRIPTION
**Pull request by ryanzhoudev**
Previously this did not work because when we cancelled/overwrote ConnectScreen, we stopped calling it's tick() method which is what tells Connection.class to do the handleDisconnection() work. So we will just do it manually now.

Also uses i18n for the messages now. Closes #2128

### CODE REVIEW

File: common/src/main/java/com/wynntils/features/ui/CustomLoadingScreenFeature.java [hunk 1]
```diff
@@ -12,29 +12,45 @@
...
             event.setCanceled(true);
+            loadingScreen.setMessage(I18n.get("feature.wynntils.customLoadingScreen.working"));
         }
         if (event.getScreen() instanceof ReceivingLevelScreen) {
             event.setCanceled(true);
-            loadingScreen.setMessage("Receiving terrain...");
+            loadingScreen.setMessage(I18n.get("feature.wynntils.customLoadingScreen.receivingTerrain"));
+        }
+
+        if (event.getScreen() instanceof DisconnectedScreen) {
```
Comment (magicus) [inline common/src/main/java/com/wynntils/features/ui/CustomLoadingScreenFeature.java]: This does not seem like the correct condition to set baseConnectScreen to null...? Or at least it should also be set to null when the ConnectScreen closes.

**Comment by magicus** [comment]
Yeah, the ConnectScreen does too much non-GUI stuff... Mojang is behind on some refactoring there... Good find!

File: common/src/main/java/com/wynntils/features/ui/CustomLoadingScreenFeature.java (hunk 1 above)
Comment (ryanzhoudev) [reply common/src/main/java/com/wynntils/features/ui/CustomLoadingScreenFeature.java]: There is no actual way to check if the ConnectScreen closes, because, well, we got rid of it and have our own. But I think what I have here is fine now. Any screen that isn't our custom screen or some un-cancelled ConnectScreen will erase it. This allows it to work during our connection, and closes it as soon as the handshake is done (including ProgressScreen, ReceivingLevelScreen, etc), it'll disappear nicely.

Comment (magicus) [reply common/src/main/java/com/wynntils/features/ui/CustomLoadingScreenFeature.java]: Ok. Sounds good then. Maybe add a shortened version of this explanation as a comment?

**Review by magicus — APPROVED** [review]

**Review by kristofbolyai — APPROVED** [review]

**Comment by kristofbolyai** [comment]
Thanks for spending time on this.
