### PR TITLE
fix: Fix ingredient pouch annotator [skip ci]

### LINKED ISSUE #2616: Ultimate Ironman pouches aren't properly recognized
To reproduce the bug, play on an ultimate ironman character, and either notice pouch item count not existing, or execute `/function get pouch_used`, it'll output `-1`.

### PR DESCRIPTION
**Pull request by ShadowCat117**
Also fixes https://github.com/Wynntils/Wynntils/issues/2616
image

### CODE REVIEW

**Review by kristofbolyai — APPROVED** [review]

**Comment by kristofbolyai** [comment]
Thanks!

File: common/src/main/java/com/wynntils/models/items/annotators/gui/IngredientPouchAnnotator.java [hunk 1]
```diff
@@ -21,15 +21,14 @@
...
 public final class IngredientPouchAnnotator implements GuiItemAnnotator {
-    private static final StyledText INGREDIENT_POUCH_NAME = StyledText.fromString("§6Ingredient Pouch");
+    private static final Pattern INGREDIENT_POUCH_PATTERN = Pattern.compile("§6[a-zA-Z0-9]+(?:'s)? Pouch");
     private static final Pattern INGREDIENT_LORE_LINE_PATTERN =
             Pattern.compile("^§f(\\d+) x §7([^§]*)(?:§[3567])? \\[§([8bde])✫(§8)?✫(§8)?✫§[3567]\\]$");
 
     @Override
     public ItemAnnotation getAnnotation(ItemStack itemStack, StyledText name) {
-        // DIAMOND_AXE when not empty, SNOW when empty
-        if (itemStack.getItem() != Items.DIAMOND_AXE && itemStack.getItem() != Items.SNOW) return null;
```
Comment (magicus) [inline common/src/main/java/com/wynntils/models/items/annotators/gui/IngredientPouchAnnotator.java:31]: I'm curious of the change between DIAMOND_AXE and IRON_HORSE_ARMOR. Have all pouches changed type to horse armor? If so, all pouches, not just ironman, would have been broken? Or are different items used for normal/ironman pouches, and now we've broken normal pouches?

Comment (kristofbolyai) [reply common/src/main/java/com/wynntils/models/items/annotators/gui/IngredientPouchAnnotator.java:31]: 90% of the items are now either an IRON_HORSE_ARMOR or a POTION since 1.21/Wynn 2.1.

Comment (magicus) [reply common/src/main/java/com/wynntils/models/items/annotators/gui/IngredientPouchAnnotator.java:31]: Ok, so this was completely broken since 2.1 then, not only for ironman? (Maybe I just got confused by the corresponding bug report.)
