### PR TITLE
fix: Call callOnConfigUpdate for disabled overlays, only call for the single enabled overlay

### LINKED ISSUE #3545: Spell inputs are not visible with parent feature disabled until config change
1. Disable Spell Cast Message Overlay
2. Leave Spell Inputs Overlay enabled with Display Original Input config as disabled
3. Join server and cast spells, the spell inputs will not be visible until changing any config (triggering `onConfigUpdate`)

SpellInputsOverlay recieves config updates via `onConfigUpdate` up until the parent feature gets disabled, at which point the spell model is not informed that the vanilla spell inputs should be shown. Either it should still recieve the config updates or they should never have been received in the first place

### PR DESCRIPTION
**Pull request by ShadowCat117**
Fixes https://github.com/Wynntils/Wynntils/issues/3545

I've only done a limited amount of testing for the moment, so this may have some side effects.

Perhaps someone who was around when the OverlayManager was written can weigh in on whether it is intentional for all enabled overlays to have `callOnConfigUpdate` be called when an overlay is disabled and not the disabled overlay as it just seems like a mistake to me

### CODE REVIEW

**Comment by magicus** [comment]
It looks like a copy/paste problem yes. Otoh, enableOverlay also seems sus. Why does it call *all* enabled overlays, and not just the one that was enabled in it? I can't see how any of this makes any sense.

**Comment by ShadowCat117** [comment]
> It looks like a copy/paste problem yes. Otoh, enableOverlay also seems sus. Why does it call _all_ enabled overlays, and not just the one that was enabled in it? I can't see how any of this makes any sense.

Excellent point, that does also seem sus

File: common/src/main/java/com/wynntils/core/consumers/overlays/OverlayManager.java [hunk 1]
```diff
@@ -94,22 +94,20 @@ public void disableOverlay(Overlay disabledOverlay) {
...
+        disabledOverlay.getConfigOptionFromString("userEnabled").ifPresent(disabledOverlay::callOnConfigUpdate);
     }
 
     public void enableOverlays(Feature parent) {
         overlayParentMap.getOrDefault(parent, List.of()).forEach(this::enableOverlay);
     }
 
-    public void enableOverlay(Overlay enableOverlay) {
-        if (!enableOverlay.shouldBeEnabled() || isEnabled(enableOverlay)) return;
+    public void enableOverlay(Overlay enabledOverlay) {
```
Comment (magicus) [inline common/src/main/java/com/wynntils/core/consumers/overlays/OverlayManager.java:104]: So maybe I'm nickpicking now, but it feels a bit odd to call the argument "enabledOverlay", since it clearly is not enabled when you call this method (or you exit very quickly). I suggest renaming it to just "overlay" (and the same with the argument to disableOverlay()).

Comment (ShadowCat117) [reply common/src/main/java/com/wynntils/core/consumers/overlays/OverlayManager.java:104]: Eh, I think it's fine. It's not "this overlay is enabled" it's "the overlay that's being enabled"

Comment (magicus) [reply common/src/main/java/com/wynntils/core/consumers/overlays/OverlayManager.java:104]: Whatever.

**Review by magicus — APPROVED** [review]
