### PR TITLE
fix: Fix descriptions of text-based settings not displaying

### LINKED ISSUE #2091: The discription of the ConfigTile doesn't get displayed when hovering a text field
https://gyazo.com/5295c4083ec5706997eb949674507ae8
https://discord.com/channels/394189072635133952/424990456435310602/1149396907060375572

### PR DESCRIPTION
**Pull request by Mcrtin**
fixes: #2091

### CODE REVIEW

File: common/src/main/java/com/wynntils/screens/settings/widgets/TextInputBoxSettingsWidget.java [hunk 1]
```diff
@@ -17,6 +20,7 @@ protected TextInputBoxSettingsWidget(Config<T> config, TextboxScreen textboxScre
         super(0, 6, width, FontRenderer.getInstance().getFont().lineHeight + 8, null, textboxScreen);
         this.config = config;
         setTextBoxInput(config.get().toString());
+        tooltip = ComponentUtils.wrapTooltips(List.of(Component.literal(config.getDescription())), 150);
```
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/screens/settings/widgets/TextInputBoxSettingsWidget.java:23]: either this is not needed or this fixes something that you didnt describe..

Comment (ShadowCat117) [reply common/src/main/java/com/wynntils/screens/settings/widgets/TextInputBoxSettingsWidget.java:23]: This sets the tooltip to be displayed, no?

It might be better to have the tooltip as a parameter in the parent constructor, then it's easier to set tooltips for any other input widgets

Comment (kristofbolyai) [reply common/src/main/java/com/wynntils/screens/settings/widgets/TextInputBoxSettingsWidget.java:23]: The other change sets the tooltip to be rendered? this just sets some variable

Comment (kristofbolyai) [reply common/src/main/java/com/wynntils/screens/settings/widgets/TextInputBoxSettingsWidget.java:23]: i would have to read the code, this is kind of weird

Comment (ShadowCat117) [reply common/src/main/java/com/wynntils/screens/settings/widgets/TextInputBoxSettingsWidget.java:23]: Yeah this sets what the tooltip will be, in `TextInputBoxWidget` the variable is just null, it's only set here, that's why I think it would be better to do in the constructor

Comment (Mcrtin) [reply common/src/main/java/com/wynntils/screens/settings/widgets/TextInputBoxSettingsWidget.java:23]: the tooltip variable refers to the field I added in `TextInputBoxWidget`. I did it like this to avoid another constructor parameter (because it is just used once) and to allow it to be changed.

**Review by kristofbolyai — APPROVED** [review]
Hm, I see now. I didn't realize the inheritance between these classes..
