### PR TITLE
fix: decouple keybind persistence from displayed labels 2 electric boogaloo

### LINKED ISSUE #3865: Rework keybinds so user displayed titles are not used as keys
See https://github.com/Wynntils/Wynntils/pull/3847#discussion_r3032325822:

> Prior to 1.21.11 we just had the plain English names for keybinds, in this case "Mount Horse" and that is the key saved to the options.txt file and what is displayed on the keybinds screen.

We should fix the keybind framework, and then rename the "Mount Horse" keybind.

### PR DESCRIPTION
**Pull request by OneNoted**
https://github.com/Wynntils/Wynntils/pull/3869 PR targeting main instead

Fixes: https://github.com/Wynntils/Wynntils/issues/3865 

*apologies for the unprofessional title!*

### CODE REVIEW

File: common/src/main/java/com/wynntils/core/keybinds/KeyBindManager.java
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/core/keybinds/KeyBindManager.java:1]: can you remove the static methods? generally managers, models, etc components follow the singleton pattern and don't contain static methods - except if they are needed for some reason in the lifecycle (eg. to be called very early in boot sequence)

File: common/src/main/java/com/wynntils/mc/mixin/accessors/OptionsLoadVisitorAccessor.java [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+ * Copyright © Wynntils 2026.
+ * This file is released under LGPLv3. See LICENSE for full license details.
+ */
+package com.wynntils.mc.mixin.accessors;
+
+import net.minecraft.nbt.CompoundTag;
+import org.spongepowered.asm.mixin.Mixin;
+import org.spongepowered.asm.mixin.gen.Accessor;
+
+@Mixin(targets = "net.minecraft.client.Options$2")
```
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/mc/mixin/accessors/OptionsLoadVisitorAccessor.java]: Can you just confirm for me this mixin works on NeoForge as well? We've had issues with a bit more special mixins not working on NeoForge due to special mappings.

**Review by kristofbolyai — APPROVED** [review]
Please answer those 2 small questions I have - otherwise this is looking great now, thank you for your contribution. We are looking forward to any other contributions, if you feel motivated.

@magicus as the original author behind the task, would you like to take a look? 

Happy Easter to both of you :)

File: common/src/main/java/com/wynntils/mc/mixin/accessors/OptionsLoadVisitorAccessor.java (hunk 1 above)
Comment (OneNoted) [reply common/src/main/java/com/wynntils/mc/mixin/accessors/OptionsLoadVisitorAccessor.java]: Conveniently, NeoForge decided to begin undergoing maintenance just now and I unfortunately don't have an instance :sob: so It'll take a bit before I can get back to you on this!

Comment (kristofbolyai) [reply common/src/main/java/com/wynntils/mc/mixin/accessors/OptionsLoadVisitorAccessor.java]: Dear neoforge in fact did not work with this - so special mixin. They remap anonymous classes to named classes as far as I am aware, hence the issue. You can decompile the NeoForge options class to see how you can refer to it.

```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [wynntils.mixins.json:accessors.OptionsLoadVisitorAccessor from mod wynntils] from phase [DEFAULT] in config [wynntils.mixins.json] FAILED during APPLY
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching val$options:Lnet/minecraft/nbt/CompoundTag; in net/minecraft/client/Options$2 for wynntils.mixins.json:accessors.OptionsLoadVisitorAccessor from mod wynntils->@Accessor[FIELD_GETTER]::wynntils$getOptions()Lnet/minecraft/nbt/CompoundTag; [ACCESSOR Applicator Phase -> wynntils.mixins.json:accessors.OptionsLoadVisitorAccessor from mod wynntils -> Apply Accessors ->  -> Locate -> wynntils.mixins.json:accessors.OptionsLoadVisitorAccessor from mod wynntils->@Accessor[FIELD_GETTER]::wynntils$getOptions()Lnet/minecraft/nbt/CompoundTag;]
```

Comment (OneNoted) [reply common/src/main/java/com/wynntils/mc/mixin/accessors/OptionsLoadVisitorAccessor.java]: Ah, great thank you.

Alright I'll try and get a follow up soon! :smile: 

*managed to jerry-rig an instance to test :partying_face:*

Comment (OneNoted) [reply common/src/main/java/com/wynntils/mc/mixin/accessors/OptionsLoadVisitorAccessor.java]: Alright, all appears to be well now after: [9783a9b](https://github.com/Wynntils/Wynntils/pull/3876/commits/9783a9b1bf45b59839f323bc8d4d9080c564d15e)

File: common/src/main/java/com/wynntils/core/keybinds/LegacyKeybindFieldAccess.java [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+package com.wynntils.core.keybinds;
+
+import java.util.function.Function;
+import net.minecraft.client.Options;
+
+public final class LegacyKeybindFieldAccess implements Options.FieldAccess {
+    private static final String MISSING_KEYBIND_SENTINEL = "__wynntils_missing_keybind__";
+
+    private final Options.FieldAccess delegate;
+    private final KeyBindManager keyBindManager;
```
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/core/keybinds/LegacyKeybindFieldAccess.java]: Can you refer to Managers.Keybind instead of having this field? - sorry for the nit

Do you know whether options loading happens before or after Manager init? Does this change the mod init order by loading managers early here?

**Comment by OneNoted** [comment]
> Please answer those 2 small questions I have - otherwise this is looking great now, thank you for your contribution. We are looking forward to any other contributions, if you feel motivated.
> 
> @magicus as the original author behind the task, would you like to take a look?
> 
> Happy Easter to both of you :)

Happy easter indeed!! 

As far as I can tell CI failure is unrelated to this branch's changes *reran spotless locally and it passes so unless I'm being very blind today it's CI flakiness*

Let me know if there's anything else I missed, good day to you both :smile: 

> Can you refer to Managers.Keybind instead of having this field? - sorry for the nit
> 
> Do you know whether options loading happens before or after Manager init? Does this change the mod init order by loading managers early here?

Sorry, I didn't refresh the gh page in time to see the reply...

File: common/src/main/resources/assets/wynntils/lang/en_us.json [hunk 3]
```diff
@@ -3726,5 +3726,60 @@
...
+  "wynntils.keybind.relayBombToParty": "Relay Bomb to Party",
+  "wynntils.keybind.resetStopwatch": "Reset Stopwatch",
+  "wynntils.keybind.saveItemToRecord": "Save Item to Item Record",
+  "wynntils.keybind.screenshotItem": "Screenshot Item",
+  "wynntils.keybind.selectForComparing": "Select for comparing",
+  "wynntils.keybind.shareItem": "Share Item",
+  "wynntils.keybind.toggleFavorite": "Favorite/Unfavorite Item",
+  "wynntils.keybind.toggleSilencer": "Toggle Silencer",
+  "wynntils.keybind.toggleStopwatch": "Toggle Stopwatch",
+  "wynntils.keybind.viewPlayer": "View Player's Gear"
```
Comment (ShadowCat117) [inline common/src/main/resources/assets/wynntils/lang/en_us.json]:
```suggestion
  "wynntils.keybind.viewPlayer": "View Player"
```

File: common/src/main/resources/assets/wynntils/lang/en_us.json [hunk 4]
```diff
@@ -3726,5 +3726,60 @@
...
+  "wynntils.keybind.openMainMap": "Open Main Map",
+  "wynntils.keybind.openMiscGuide": "Open Misc Guide",
+  "wynntils.keybind.openOverlayFreeMove": "Open Overlay Free Move",
+  "wynntils.keybind.openOverlayMenu": "Open Overlay Menu",
+  "wynntils.keybind.openPartyManagement": "Open Party Management Screen",
+  "wynntils.keybind.openPowerGuide": "Open Powder Guide",
+  "wynntils.keybind.openTerritoryMenu": "Open Territory Menu",
+  "wynntils.keybind.openTomeGuide": "Open Tome Guide",
+  "wynntils.keybind.openWynntilsMenu": "Open Wynntils Menu",
+  "wynntils.keybind.progressNpcDialogue": "Progress NPC Dialogue",
```
Comment (ShadowCat117) [inline common/src/main/resources/assets/wynntils/lang/en_us.json]: Is this keybind still around? It should be removed

File: common/src/main/java/com/wynntils/services/hint/HintService.java [hunk 5]
```diff
@@ -123,20 +124,19 @@ private MutableComponent formatHint(String hint) {
...
+        if (keyMapping == null) {
+            WynntilsMod.info("Skipping hint due to unknown keybind " + keybindName);
+            return Component.empty();
+        }
+
+        String translated = keyMapping.getTranslatedKeyMessage().getString();
+        if (translated.equals(I18n.get(UNBOUND_KEY))) {
+            WynntilsMod.info("Skipping hint due to unbound key");
+            return Component.empty();
         }
```
Comment (ShadowCat117) [inline common/src/main/java/com/wynntils/services/hint/HintService.java:137]: Although this does work, we should change the hints on https://github.com/Wynntils/Static-Storage/blob/main/Data-Storage/hint_messages.json to use the new key instead of the old names, shouldn't affect old versions as it will simply fail to find the keybind

File: common/src/main/resources/assets/wynntils/lang/en_us.json [hunk 6]
```diff
@@ -3726,5 +3726,60 @@
   "utils.wynntils.time.now": "now",
   "utils.wynntils.time.past": "%s ago",
   "utils.wynntils.time.second": "%d second",
-  "utils.wynntils.time.seconds": "%d seconds"
+  "utils.wynntils.time.seconds": "%d seconds",
+  "wynntils.keybind.cancelNpcAutoProgress": "Cancel Dialog Auto Progress",
```
Comment (ShadowCat117) [inline common/src/main/resources/assets/wynntils/lang/en_us.json]: And this one too

File: common/src/main/java/com/wynntils/core/keybinds/LegacyKeybindFieldAccess.java (hunk 2 above)
Comment (OneNoted) [reply common/src/main/java/com/wynntils/core/keybinds/LegacyKeybindFieldAccess.java]: > Can you refer to Managers.Keybind instead of having this field? - sorry for the nit
> 
> Do you know whether options loading happens before or after Manager init? Does this change the mod init order by loading managers early here?

This should not affect init order: `Options.load()` was already caling into `Managers.KeyBind` through `registerKeybinds()` in the mixin head, so this follow-up doesn't load any managers earlier than before.

File: common/src/main/java/com/wynntils/services/hint/HintService.java (hunk 5 above)
Comment (OneNoted) [reply common/src/main/java/com/wynntils/services/hint/HintService.java:137]: https://github.com/Wynntils/Static-Storage/pull/423
