### PR TITLE
fix: Trade market buttons appear late sometimes [skip ci]

### LINKED ISSUE #3126: Market buttons don't display consistently in 3.0.6
After updating Wynntils with `/wynntils update` (and updating everything else because [the update command unexpectedly bumped me to 1.21.4](https://github.com/Wynntils/Wynntils/issues/3124)), I started noticing issues when trying to use the trade market. Buttons like "sell all" would only display some of the time. Need a screenshot or anything? (I can't get one at this instant because I'm in the queue for a world)

### PR DESCRIPTION
**Pull request by ryanzhoudev**
Closes #3126. Apparently the event/packet comes back too fast and we aren't on the ContainerScreen sometimes.

### CODE REVIEW

**Comment by ShadowCat117** [comment]
Is that ContainerModel doesn't know we're on the right container or we actually aren't on a ContainerScreen? That seems a bit odd if the latter. Can we use the SetContent event instead, maybe that will be late enough

**Comment by ryanzhoudev** [comment]
The latter. I'll check with that event

**Comment by ryanzhoudev** [comment]
It appears SetContent isn't triggered when the user first puts an item into the sell slot. This first time, SetSlot is triggered at the correct time and we're already in the ContainerScreen. Any time after that when the buttons are clicked or the slot is updated, SetContent is triggered at the correct time.

We can either have one SetSlot event with this one tick delay, or both events with no delay on either.

**Comment by ShadowCat117** [comment]
Hmm, maybe the logic for figuring out what item is currently being sold/bought should be moved to the tm model, then the features can just worry about creating the widgets?

**Comment by ryanzhoudev** [comment]
That is probably a good idea

**Comment by magicus** [comment]
> maybe the logic for figuring out what item is currently being sold/bought should be moved to the tm model,

:+1:

I'll just keep repeating my mantra: the more logic we can put in the models, the more powerful Wynntils gets. If the model knows which items we are buying, that allows for easy features such as playing a fanfare whenever you buy a favourited item, or whatever.

**Review by ShadowCat117 — COMMENTED** [review]
Price match changes look great! I think you just need to move the `getSoldItemName` from the bulk sell feature to the model and fix the tests then this will be good to go

File: common/src/main/java/com/wynntils/models/trademarket/TradeMarketModel.java [hunk 1]
```diff
@@ -242,23 +271,59 @@ public int getUnitPrice() {
...
+        if (itemStack == ItemStack.EMPTY) return null;
+
+        StyledText itemStackName = StyledText.fromComponent(itemStack.getHoverName());
+        if (itemStackName.getString(PartStyle.StyleType.NONE).equals(SOLD_ITEM_SLOT)) return null;
+
+        Matcher m = itemStackName.getMatcher(SELL_ITEM_NAME_PATTERN);
+        if (!m.matches()) return null;
+
+        return m.group(1);
+    }
```
Comment (ShadowCat117) [inline common/src/main/java/com/wynntils/models/trademarket/TradeMarketModel.java]: Sorry should have been more clear, you should do this always in the method below, then the feature can just get the name without having to pass in the chest contents

**Review by ShadowCat117 — APPROVED** [review]
Nice, this is much better!
