### PR TITLE
fix: Fix element font handling in abbreviate mob health and focused mob overlay

### LINKED ISSUE #3407: Boss Bar Health Has broken icons
Icons are broken on the latest version of wynntils (at the time of writing it is v3.2.2)

Image

### PR DESCRIPTION
**Pull request by ShadowCat117**
Fixes https://github.com/Wynntils/Wynntils/issues/3407

Also adds an abbreviate config to the overlay instead of relying on the feature

Fixed Overlay
image

Abbreviate mob health was also having issues with the styling so now it only changes the necessary part. Wynn have also abbreviated mob health by default since 2.1 but they don't abbreviate for under 10k like ours does and they also don't do it for the lootrun defend and destroy challenges. Have made it use a lower case "k" or "m" to match the Wynn styling

Broken abbreviation
image

Fixed abbreviation
image

### CODE REVIEW

File: common/src/main/java/com/wynntils/models/combat/type/MobElementals.java [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+    }
+
+    private void appendElementGroup(MutableComponent text, List<Element> elements, String label, boolean addSpace) {
+        if (elements.isEmpty()) return;
+
+        for (Element element : elements) {
+            text.append(Component.literal(element.getSymbol())
+                    .withStyle(Style.EMPTY
+                            .withFont(ResourceLocation.withDefaultNamespace("common"))
+                            .withColor(element.getColorCode())));
```
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/models/combat/type/MobElementals.java:35]: Magicus has been asking for this, and now I want it too. Can we have a model where you can get all these special components / StyledTexts which require a font and also special unicode characters or both? It would be also useful for maintenance in the future. Although, since it is used so thoroughly, maybe we should have a file with the constants so we dont mess with class loading order.

**Review by kristofbolyai — APPROVED** [review]

File: common/src/main/java/com/wynntils/models/combat/type/MobElementals.java (hunk 1 above)
Comment (ShadowCat117) [reply common/src/main/java/com/wynntils/models/combat/type/MobElementals.java:35]: I won't do it for this pr but I'll try get around to it some point soon, do you think you could write up an issue for it?
