### PR TITLE
fix: Inventory texture disappears during bulk buy

### LINKED ISSUE #3141: Bulk buy widget renderItem causes inventory background to disappear
Also makes the highlights have a dark background but that might get fixed with https://github.com/Wynntils/Wynntils/pull/3136

Image

With renderItem removed

Image

### PR DESCRIPTION
**Pull request by ryanzhoudev**
Closes #3141

### CODE REVIEW

**Comment by ryanzhoudev** [comment]
I know this .toString() contains in a render method is incredibly sketchy, but I am under the impression that this should just be a temporary fix for 1.21.4? At least I hope..

The alternative and I guess "more proper" way is a 4-5 deep set of AW entries to go into RenderType.CompositeRenderType, its state() method, the CompositeState class, one or more of the TextureStateShards in there, and in those state shards, steal the ResourceLocation and compare it to a ResourceLocation based on this string anyway.

File: common/src/main/java/com/wynntils/screens/bulkbuy/widgets/BulkBuyWidget.java [hunk 1]
```diff
@@ -26,6 +27,7 @@ public class BulkBuyWidget extends AbstractWidget {
 
     private final int originalX;
     private final AnimationPercentage animationPercentage;
+    private final ItemStackRenderState scratchItemStackRenderState = new ItemStackRenderState();
```
Comment (ShadowCat117) [inline common/src/main/java/com/wynntils/screens/bulkbuy/widgets/BulkBuyWidget.java]: Leftover

File: common/src/main/java/com/wynntils/utils/render/RenderUtils.java [hunk 2]
```diff
@@ -758,6 +764,41 @@ public static void renderItem(GuiGraphics guiGraphics, ItemStack itemStack, int
...
     }
 
+    /**
+     * Significantly derived from {@link GuiGraphics#renderItem(LivingEntity, Level, ItemStack, int, int, int, int)}
+     * May be a 1.21.4 only bandage fix - wasn't required in 1.21.1.
+     * Needs following AWs:
+     * field MultiBufferSource$BufferSource fixedBuffers
+     */
+    public static void renderMaskRespectingItem(GuiGraphics guiGraphics, ItemStack itemStack, int x, int y) {
+        ItemStackRenderState scratchItemStackRenderState = new ItemStackRenderState();
```
Comment (ShadowCat117) [inline common/src/main/java/com/wynntils/utils/render/RenderUtils.java]: Can this be made a constant or does it need to be made here each render?

**Review by ShadowCat117 — CHANGES_REQUESTED** [review]

File: common/src/main/java/com/wynntils/utils/render/RenderUtils.java (hunk 2 above)
Comment (ryanzhoudev) [reply common/src/main/java/com/wynntils/utils/render/RenderUtils.java]: For the moment it looks like it can be made a constant.

File: common/src/main/java/com/wynntils/utils/render/RenderUtils.java [hunk 3]
```diff
@@ -758,6 +767,45 @@ public static void renderItem(GuiGraphics guiGraphics, ItemStack itemStack, int
         guiGraphics.renderItem(itemStack, x, y);
     }
 
+    /**
+     * Significantly derived from {@link GuiGraphics#renderItem(LivingEntity, Level, ItemStack, int, int, int, int)}
+     * May be a 1.21.4 only bandage fix - wasn't required in 1.21.1.
+     * Needs following AWs:
+     * field MultiBufferSource$BufferSource fixedBuffers
+     */
+    public static void renderMaskRespectingItem(GuiGraphics guiGraphics, ItemStack itemStack, int x, int y) {
```
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/utils/render/RenderUtils.java]: Can you put the difference between the original method and this one here? And/or also in line, preferably in well separated way.

Comment (ryanzhoudev) [reply common/src/main/java/com/wynntils/utils/render/RenderUtils.java]: Kind of done, I think this is pretty much as good as spotless will let it.

**Review by magicus — APPROVED** [review]
Much better!

**Review by ShadowCat117 — APPROVED** [review]
Looks good! I'll save merging this till after todays patch in case we need to do a release to fix some issues with that
