### PR TITLE
fix: dry streak messages

### LINKED ISSUE #4016: Fix lootrun dry streak message
Either the unicode characters need to be stripped with `WynnUtils#stripItemNameMarkers` or check for `NamedItemProperty` property on the WynnItem and use that to display name

Image

Can replace the tier here with legendary for easy debugging https://github.com/Wynntils/Wynntils/blob/8cc178a4384474703539c07306edce80ce69aa0f/common/src/main/java/com/wynntils/models/lootrun/LootrunModel.java#L519

### PR DESCRIPTION
**Pull request by DevChromium**
image
image

Fixes https://github.com/Wynntils/Wynntils/issues/4016
Had to add a new marker to  `WynnUtils#stripItemNameMarkers`, but this is an unknown marker for now. Unless anyone knows what it is used for.

### CODE REVIEW

File: common/src/main/java/com/wynntils/utils/wynn/WynnUtils.java [hunk 1]
```diff
@@ -9,6 +9,7 @@
 public final class WynnUtils {
     private static final String ITEM_NAME_MARKER = "\uDAFC\uDC00";
     private static final String UNIDENTIFIED_ITEM_MARKER = "\uDB00\uDC02";
+    private static final String UNKNOWN_MARKER = "\uE008";
```
Comment (ShadowCat117) [inline common/src/main/java/com/wynntils/utils/wynn/WynnUtils.java:13]: Just add a comment to this saying the purpose is currently unknown but is present on some items

**Comment by ShadowCat117** [comment]
Do tomes need this as well, aspects are fine but tomes have the new tooltip style

**Comment by DevChromium** [comment]
Will check tomes in a second, they might need it as well.

**Review by ShadowCat117 — APPROVED** [review]
