### PR TITLE
ObjectivesOverlayFeature: Fix render height when multiline

### LINKED ISSUE #298: Incorrect offsets for Daily objective rendering when multi line
image

### PR DESCRIPTION
**Pull request by kristofbolyai**
Fixes #298

### CODE REVIEW

**Comment by magicus** [comment]
@kristofbolyai This also includes https://github.com/Wynntils/Artemis/pull/305? Seems you did not base the fix on main.

**Comment by kristofbolyai** [comment]
Just fixed it.

File: common/src/main/java/com/wynntils/features/user/overlays/ObjectivesOverlayFeature.java [hunk 1]
```diff
@@ -181,8 +183,13 @@ public void render(PoseStack poseStack, float partialTicks, Window window) {
             final int barHeight = this.enableProgressBar ? 5 : 0;
             final int barWidth = 182;
             final float actualBarHeight = barHeight * (this.getWidth() / barWidth);
-            final float renderedHeight = SPACE_BETWEEN + 9 + actualBarHeight;
-            final float fullHeight = renderedHeight * objectives.size() - SPACE_BETWEEN;
+            final float renderedHeightWithoutTextHeight = SPACE_BETWEEN + actualBarHeight;
+            final float fullHeight = (float) (renderedHeightWithoutTextHeight * objectives.size()
```
Comment (magicus) [inline common/src/main/java/com/wynntils/features/user/overlays/ObjectivesOverlayFeature.java:187]: If we ever start doing something like this in some other place, I think we should move it to a utility class, but for now it can reside here.

Comment (magicus) [reply common/src/main/java/com/wynntils/features/user/overlays/ObjectivesOverlayFeature.java:187]: It's kind of icky. I assume it's doing the right thing but I'm a bit too tired to really wrap my head around it, and convince myself that it is. This is no complaint on your code, I believe the problem is actually more complex than one would think at first glance, and complex problems require complex solutions.

**Review by magicus — APPROVED** [review]
