### PR TITLE
ManaBar: Fix food render event

### LINKED ISSUE #177: Horse health bar covers up mana overlay while on horse
image

### PR DESCRIPTION
**Pull request by kristofbolyai**
This fixes a forge bug where mana bar was not rendered while on a mount, and an all loader bug where we did not disable the rendering of mounts' health. On Wynncraft, mount health is useless, hence why I opt to always disable it. 

Fixes #177

### CODE REVIEW

**Review by Incompleteusern — DISMISSED** [review]

File: forge/src/main/java/com/wynntils/forge/mixins/ForgeIngameGuiMixin.java [hunk 1]
```diff
@@ -38,4 +38,13 @@ public void onRenderFoodPre(int width, int height, PoseStack poseStack, Callback
             ci.cancel();
         }
     }
+
+    // The render food mixin above does not get called, we need this as a replacement.
```
Comment (magicus) [inline forge/src/main/java/com/wynntils/forge/mixins/ForgeIngameGuiMixin.java]:
```suggestion
    // The render food mixin above does not get called when riding a horse, we need this as a replacement.
```

**Review by Incompleteusern — APPROVED** [review]

**Review by magicus — APPROVED** [review]
