### PR TITLE
fix: Update profession progress on failed gathers [skip ci]

### LINKED ISSUE #2817: Profession XP is not updated when refining fails or alt resources are gathered
When failing to refine common materials like Oak, or when gathering alternative resources such as Bamboo or Voidgloom, the Profession XP gained is not reflected in the XP Gain Message or in the overlays that use `prof_pct()` or `prof_xpm_raw()`.

In my environment, I tested gathering Starfish, Oak, Spruce, Voidstone, and Hemp. XP was reflected when refining succeeded, but not when refining failed. Additionally, XP was not reflected when gathering Abyssal Matter, Bamboo, Flerisi Tree, and Voidgloom. I have not tested Larbonic Geode due to insufficient Mining Level, but it is expected that XP will not be reflected for it as well.

Other information is as follows:
- Wynntils version: 2.1.1
- Mod loader: fabric-loader-0.16.2-1.21.1
- Other mods: None
- Operating system: Windows 10

### PR DESCRIPTION
**Pull request by ShadowCat117**
Bit of a rework to how we handle the labels, using the entity id to keep track of which nodes we've already checked instead of the position and getting the material profile from just the label instead of a combination of inventory and label.

The labels from harvesting no longer seem to move as seen in https://github.com/Wynntils/Wynntils/issues/2586 so that issue shouldn't appear again, I tested that exact tree shown in the issue and it did not trigger twice.

Does not fully close https://github.com/Wynntils/Wynntils/issues/2817 as it doesn't handle the alternate resources, will follow up with that soon

### CODE REVIEW

**Comment by kristofbolyai** [comment]
> Does not fully close #2817

Github sure does think so though :)

File: common/src/main/java/com/wynntils/models/profession/label/GatheringNodeHarvestLabelParser.java [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+
+                if (materialMatcher.matches()) {
+                    String type = materialMatcher.group("type");
+                    String material = materialMatcher.group("material");
+                    String tierGroup = materialMatcher.group("tier");
+                    int tier =
+                            switch (tierGroup) {
+                                case "§e✫✫§8✫" -> 2;
+                                case "§e✫✫✫" -> 3;
+                                default -> 1;
```
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/models/profession/label/GatheringNodeHarvestLabelParser.java]: Extract the constants into static strings, or make a "tier parser" function. Also, it'd be wiser to reorder the switch case, so the order is increasing or decreasing.

Comment (ShadowCat117) [reply common/src/main/java/com/wynntils/models/profession/label/GatheringNodeHarvestLabelParser.java]: Uses same tier pattern as MaterialAnnotator now and parses it inside MaterialProfile

**Review by kristofbolyai — APPROVED** [review]
