### PR TITLE
fix: Fix wrong minimum hover/render alphas

### LINKED ISSUE #2548: [MapData] - Minimum visibility to render is slightly off, allowing hovering unrendered features
image

1 more zoom step
image

### PR DESCRIPTION
**Pull request by kristofbolyai**
Fixes #2548

It seems like OpenGL ignores the first and last 10% render alpha, so `0.1f` is considered as `0f` alpha, and `0.9f` is considered as `1f`.
Taking all these into account, I've found two different, weird behavior:
- Due to `hoverAlphaFactor`, fully visible features were still rendered with `0.9f` alpha. Due to the weird OpenGL alphas, this was considered as `1f`.
- `0.1f` alphas were considered as rendered, but did not render, causing features to become rendered on hover, although there were invisible (#2548)

It seems like `hoverAlphaFactor` was introduced in `LabelPoi`, but I can't find any reason for their existence. It seems magicus ported this design detail, to preserve the original behavior, which is wrong, or confusing, at the very least.

# Debug Screenshots
## Old behavior
image
Observe that features with `0.075f` alpha is fully invisible. It can also be observed that features with "max" visibility are rendered with `0.9f` alpha (but are shown with max alpha).

## New Behavior
image
image
image
Observe that all rendered alphas are actually represented in the rendering of the icons. Also observe that fully visible features are rendered with the correct, `1f` alphas.

### CODE REVIEW

File: common/src/main/java/com/wynntils/services/mapdata/MapFeatureRenderer.java [hunk 1]
```diff
@@ -71,16 +74,25 @@ public static void renderMapFeature(
                     0,
                     iconWidth,
                     iconHeight);
+            BufferedFontRenderer.getInstance()
```
Comment (magicus) [inline common/src/main/java/com/wynntils/services/mapdata/MapFeatureRenderer.java]: What happened here?

**Comment by magicus** [comment]
And yeah, I don't know about hoverAlphaFactor, just copied it from the old code as you say.

File: common/src/main/java/com/wynntils/services/mapdata/MapFeatureRenderer.java (hunk 1 above)
Comment (kristofbolyai) [reply common/src/main/java/com/wynntils/services/mapdata/MapFeatureRenderer.java]: Left behind debug code to render the zoom level. I've thought I force pushed to remove this.. Anyways, does this look acceptable otherwise?

**Review by magicus — APPROVED** [review]
Yes, looks good. Thanks!
