### PR TITLE
fix: Properly port item record to 2.1 and Minecraft 1.21.4

### LINKED ISSUE #3246: Update the item record
The item record still uses pre 2.1 methods of storing the ItemStack meaning items are not displayed as they actually are after changes in the resource pack.

The screen also still needs proper porting to 1.21.4 as it has the dark overlay issue and rendering issues when not hovering a slot

### PR DESCRIPTION
**Pull request by ShadowCat117**
Closes https://github.com/Wynntils/Wynntils/issues/3246

Fixes rendering issues from the 1.21.4 port.

Gear now uses the api information to get the itemstack so unless the api is outdated we don't have to worry about that.

Crafted items still use damage values for their alternate textures, even if they use custom model data I don't think we'd be able to keep that updated with resource pack changes.

### CODE REVIEW

**Comment by ShadowCat117** [comment]
I did not have any pre 2.1 crafted items in my item record so I have no idea how they will look but normal gear worked fine

File: common/src/main/java/com/wynntils/services/itemrecord/type/SavedItem.java [hunk 1]
```diff
@@ -137,5 +151,6 @@ public JsonElement serialize(SavedItem src, Type typeOfSrc, JsonSerializationCon
         }
     }
 
-    private record ItemStackInfo(int itemId, int damage, boolean unbreakable, int color) {}
+    private record ItemStackInfo(
+            String registeredItemName, CustomModelData customModelData, int itemId, int damage, int color) {}
```
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/services/itemrecord/type/SavedItem.java]: Is item name as a string the best we can do? I've thought about using item codecs to serialize the whole item. As MC maintains that, it should be okay-ishly future compatible. 

From a quick look at https://docs.fabricmc.net/develop/codecs writing a gson serializer seems simple enough.

**Review by kristofbolyai — APPROVED** [review]
Thank you!
