### PR TITLE
fix: Wrap overflowing splash text

### LINKED ISSUE #1855: Wrap long splashes
When the splash text is too long, it is written outside the book instead of wrapped. This looks horrible. See e.g. https://github.com/Wynntils/Artemis/pull/1833

### PR DESCRIPTION
**Pull request by ryanzhoudev**
Fixes #1855

image

### CODE REVIEW

File: common/src/main/java/com/wynntils/screens/wynntilsmenu/WynntilsMenuScreen.java [hunk 1]
```diff
@@ -356,19 +361,28 @@ private static void renderPlayerInfo(PoseStack poseStack, int mouseX, int mouseY
...
-                        Texture.QUEST_BOOK_BACKGROUND.width(),
-                        Texture.QUEST_BOOK_BACKGROUND.height() - 45,
-                        0,
-                        CommonColors.MAGENTA,
-                        HorizontalAlignment.CENTER,
-                        TextShadow.NONE);
+        String currentSplash = Services.Splash.getCurrentSplash() == null ? "" : Services.Splash.getCurrentSplash();
+        if (!splashText.equals(currentSplash)) {
+            // No need to calculate this every frame
+            wrappedSplash = StringUtils.wrap(currentSplash, Texture.QUEST_BOOK_BACKGROUND.width() / 2 - 20);
```
Comment (magicus) [inline common/src/main/java/com/wynntils/screens/wynntilsmenu/WynntilsMenuScreen.java]: FYI: We already have `RenderedStringUtils.wrapTextBySize()`.

**Review by kristofbolyai — COMMENTED** [review]
Hey, sorry for not seeing this before, I saw magicus' review and didn't think further. But, this is overcomplicated. You have to change a single number, in the original code, the maxWidth variable. Yes, it will recalculate in render time. We are in a screen. It does not matter.

**Review by magicus — APPROVED** [review]
