### PR TITLE
Beacon Changes

### LINKED ISSUE #521: Waypoint beacon rendering breaks with Sodium after F5 is pressed
After f5 is pressed with the latest version of sodium, the beacon renders incorrectly as a black column with a small moving red strip and red glow region, as below
image

### PR DESCRIPTION
**Pull request by Incompleteusern**
This pr normalizes beacon distance from the player to remain within render distance.

Also closes #521

### CODE REVIEW

File: common/src/main/java/com/wynntils/utils/MathUtils.java [hunk 1]
```diff
@@ -75,6 +75,10 @@ public static float magnitude(float x, float y) {
         return (float) Math.sqrt(x * x + y * y);
     }
 
+    public static float magnitude(double x, double y) {
+        return (float) Math.sqrt(x * x + y * y);
+    }
+
```
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/utils/MathUtils.java]: Why? We have the float version already? I can see this added but then remove the float cast and return a double

Comment (Incompleteusern) [reply common/src/main/java/com/wynntils/utils/MathUtils.java]: Oops. On a tangent, most `MathUtils` methods can be wholesale replaced with methods from `Mth`

File: common/src/main/java/com/wynntils/features/user/BeaconBeamFeature.java [hunk 2]
```diff
@@ -47,35 +47,45 @@ public void onTrackedQuestUpdate(TrackedQuestUpdateEvent event) {
...
 
     @SubscribeEvent
-    public void onRenderLevelLast(RenderLevelLastEvent event) {
+    public void onRenderLevelLast(RenderTileLevelLastEvent event) {
         if (CompassModel.getCompassLocation().isEmpty()) return;
 
         PoseStack poseStack = event.getPoseStack();
-        MultiBufferSource.BufferSource bufferSource =
-                MultiBufferSource.immediate(Tesselator.getInstance().getBuilder());
+        MultiBufferSource.BufferSource bufferSource = MultiBufferSource.immediate(new BufferBuilder(256));
```
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/features/user/BeaconBeamFeature.java]: Where did 256 come from?

File: common/src/main/java/com/wynntils/features/user/BeaconBeamFeature.java [hunk 3]
```diff
@@ -47,35 +47,45 @@ public void onTrackedQuestUpdate(TrackedQuestUpdateEvent event) {
...
-        Camera camera = McUtils.mc().gameRenderer.getMainCamera();
-        poseStack.translate(-camera.getPosition().x, -camera.getPosition().y, -camera.getPosition().z);
+        double dx = location.x - camera.x;
+        double dy = location.y - camera.y;
+        double dz = location.z - camera.z;
 
-        Location location = CompassModel.getCompassLocation().get();
-        poseStack.translate(location.x, location.y, location.z);
+        double distance = MathUtils.magnitude(dx, dz);
+        int maxDistance = (McUtils.mc().options.renderDistance - 1) * 16;
```
Comment (kristofbolyai) [inline common/src/main/java/com/wynntils/features/user/BeaconBeamFeature.java]: this might be a stupid question but why renderDistance - 1? Why not renderdistance?

File: common/src/main/java/com/wynntils/features/user/BeaconBeamFeature.java (hunk 2 above)
Comment (Incompleteusern) [reply common/src/main/java/com/wynntils/features/user/BeaconBeamFeature.java]: I don't remember, going to revert

File: common/src/main/java/com/wynntils/features/user/BeaconBeamFeature.java (hunk 3 above)
Comment (Incompleteusern) [reply common/src/main/java/com/wynntils/features/user/BeaconBeamFeature.java]: Also oops

File: common/src/main/java/com/wynntils/features/user/BeaconBeamFeature.java (hunk 2 above)
Comment (kristofbolyai) [reply common/src/main/java/com/wynntils/features/user/BeaconBeamFeature.java]: Does this even have to be changed?

Comment (kristofbolyai) [reply common/src/main/java/com/wynntils/features/user/BeaconBeamFeature.java]: Perhaps use `MultiBufferSource.BufferSource source = McUtils.mc().renderBuffers().bufferSource();`?

Comment (Incompleteusern) [reply common/src/main/java/com/wynntils/features/user/BeaconBeamFeature.java]: Yeah, that is what is used internally

**Review by kristofbolyai — APPROVED** [review]
Looks good to me
